export type ContentBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "list"; items: string[] };

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  readTime: string;
  date: string;
  image: string;
  content: ContentBlock[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "private-limited-vs-llp-vs-opc",
    title: "Private Limited vs LLP vs OPC: Which Structure Fits Your Startup",
    excerpt: "The single most important decision a founder makes before incorporation — and the one most often gotten wrong.",
    category: "Company Registration",
    readTime: "7 min read",
    date: "2 Jul 2026",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=900&q=80",
    content: [
      { type: "p", text: "Every founder eventually asks the same question: should I register a Private Limited Company, an LLP, or an OPC? The honest answer is that it depends less on how big you want to become and more on three concrete things — whether you plan to raise outside capital, how many people are involved in ownership, and how much compliance overhead you're willing to carry." },
      { type: "h2", text: "Private Limited Company" },
      { type: "p", text: "This is the default choice for anything investor-facing. Only a Private Limited Company can issue equity shares, create an ESOP pool, or take on institutional funding cleanly — VCs and angel investors are structurally set up to invest in companies, not LLPs. The tradeoff is compliance: mandatory statutory audit regardless of turnover, annual filings (AOC-4, MGT-7), a board that must meet regularly, and DIN/DIR-3 KYC obligations for every director." },
      { type: "h2", text: "LLP (Limited Liability Partnership)" },
      { type: "p", text: "An LLP gives you the liability protection of a company with a far lighter compliance load — no mandatory audit below ₹40 lakh turnover or ₹25 lakh capital contribution, no board meeting requirements, and simpler annual filings (just Form 11 and Form 8). The catch: you cannot raise equity funding in an LLP, and converting an LLP to a Private Limited Company later is possible but adds cost and paperwork you'd have avoided by choosing correctly upfront." },
      { type: "h2", text: "One Person Company (OPC)" },
      { type: "p", text: "An OPC exists for exactly one scenario — a single founder who wants limited liability without bringing in a co-founder or investor. It converts automatically into a Private Limited Company if turnover crosses ₹2 crore or paid-up capital crosses ₹50 lakh, so treat it as a starting point, not a permanent structure." },
      { type: "h2", text: "A Simple Way to Decide" },
      { type: "list", items: [
        "Raising VC/angel money in the next 2–3 years → Private Limited Company",
        "Professional services firm, consulting, or a partnership with no fundraising plans → LLP",
        "Solo founder, no co-founder yet, want to test an idea with limited liability → OPC",
      ] },
      { type: "p", text: "The cost of switching later is real but not catastrophic — plenty of businesses convert a proprietorship or LLP into a Private Limited Company once they raise their first round. What's harder to undo is a Private Limited Company's compliance burden sitting on a business that never needed it in the first place." },
    ],
  },
  {
    slug: "private-limited-company-registration-guide",
    title: "Complete Guide to Private Limited Company Registration in India",
    excerpt: "Documents, timeline, government fees, and the exact SPICe+ process — everything before you file.",
    category: "Company Registration",
    readTime: "8 min read",
    date: "28 Jun 2026",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&q=80",
    content: [
      { type: "p", text: "Private Limited Company registration in India runs entirely through the MCA's SPICe+ (Simplified Proforma for Incorporating Company Electronically Plus) web form, which bundles name reservation, incorporation, PAN, TAN, EPFO, ESIC, and GST registration into a single filing." },
      { type: "h2", text: "Documents You'll Need" },
      { type: "list", items: [
        "PAN and Aadhaar of all proposed directors and shareholders",
        "Passport-size photographs",
        "Proof of registered office (electricity bill/rent agreement + NOC from the owner)",
        "Digital Signature Certificate (DSC) for at least one director",
      ] },
      { type: "h2", text: "The Process, Step by Step" },
      { type: "list", items: [
        "Obtain DSC for proposed directors",
        "Reserve a company name via Part A of SPICe+ (or check availability first — see our free Company Name Search tool)",
        "File Part B of SPICe+ with MOA, AOA, and director/subscriber details",
        "Receive Certificate of Incorporation (COI) with CIN, along with PAN and TAN",
        "Open a current bank account and deposit subscribed capital within 180 days",
      ] },
      { type: "h2", text: "Minimum Requirements" },
      { type: "p", text: "You need a minimum of 2 directors and 2 shareholders (they can be the same people), at least one director who is an Indian resident, and there is no minimum capital requirement — you can incorporate with as little as ₹1 as authorised capital, though most founders start with ₹1 lakh for practical banking reasons." },
      { type: "h2", text: "Timeline and Cost" },
      { type: "p", text: "A clean application with all documents in order typically gets approved in 7–10 working days. Government fees scale with authorised capital (roughly ₹500 at the lowest slab, rising with capital), and professional fees for a CA/CS-assisted filing usually range from ₹6,000–₹10,000 depending on complexity — use our Company Registration Cost Calculator for a state-wise, capital-wise breakdown." },
      { type: "h2", text: "Common Rejection Reasons" },
      { type: "p", text: "The RUN/SPICe+ name-reservation step gets rejected far more often than the incorporation itself — usually because the proposed name is too similar to an existing registered company or trademark, or because it includes a restricted word (e.g. \"National\", \"Bank\") without the required government approval. Run your proposed name through a name-availability check before filing to avoid losing the reservation fee twice." },
    ],
  },
  {
    slug: "llp-registration-process-cost",
    title: "LLP Registration: Process, Cost & Compliance Explained",
    excerpt: "Lower compliance, full liability protection — here's exactly how to register and what it costs.",
    category: "Company Registration",
    readTime: "6 min read",
    date: "24 Jun 2026",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=900&q=80",
    content: [
      { type: "p", text: "An LLP needs a minimum of two designated partners, at least one of whom must be an Indian resident. Unlike a Private Limited Company, there's no concept of authorised/paid-up share capital — partners contribute capital as agreed in the LLP Agreement, which also governs profit-sharing, decision-making, and admission/exit of partners." },
      { type: "h2", text: "Registration Steps" },
      { type: "list", items: [
        "Obtain Digital Signature Certificate (DSC) and Designated Partner Identification Number (DPIN) for partners",
        "Reserve the LLP name via the RUN-LLP service",
        "File incorporation form FiLLiP with the Registrar",
        "Draft and file the LLP Agreement (Form 3) within 30 days of incorporation",
      ] },
      { type: "h2", text: "Ongoing Compliance" },
      { type: "p", text: "This is where an LLP genuinely wins over a Private Limited Company for small professional firms and consultancies. There's no mandatory statutory audit unless turnover exceeds ₹40 lakh or capital contribution exceeds ₹25 lakh. The only two recurring ROC filings are Form 11 (Annual Return, due 30 May) and Form 8 (Statement of Account & Solvency, due 30 October) — no board meetings, no company secretary requirement, no AGM." },
      { type: "h2", text: "Taxation" },
      { type: "p", text: "LLPs are taxed at a flat 30% on profits (plus surcharge and cess where applicable), with no dividend distribution tax concept since partners simply draw profit shares. There's no small-company concessional rate the way there is for some Private Limited Companies, which is worth factoring in if profits are expected to be modest in the early years." },
      { type: "h2", text: "When an LLP Is the Wrong Choice" },
      { type: "p", text: "If you plan to raise institutional funding, offer ESOPs, or eventually list the business, don't start as an LLP — conversion to a Private Limited Company later is possible under the Companies Act but adds legal cost, a fresh set of filings, and time you'd rather spend building the business." },
    ],
  },
  {
    slug: "opc-registration-solo-founders",
    title: "One Person Company (OPC): Is It Right for Solo Founders?",
    excerpt: "Full ownership, limited liability, and a mandatory nominee — the tradeoffs solo founders should know.",
    category: "Company Registration",
    readTime: "5 min read",
    date: "20 Jun 2026",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=900&q=80",
    content: [
      { type: "p", text: "An OPC lets a single individual incorporate a company and enjoy limited liability protection — something a sole proprietorship simply cannot offer, since a proprietor's personal assets remain fully exposed to business liabilities." },
      { type: "h2", text: "Who Can Incorporate an OPC" },
      { type: "p", text: "Only an Indian citizen and resident (someone who has stayed in India for at least 120 days in the preceding financial year) can be the sole member of an OPC. A nominee — also an Indian citizen and resident — must be named at incorporation, since the nominee automatically becomes the member if the original owner dies or becomes incapacitated." },
      { type: "h2", text: "Key Restrictions" },
      { type: "list", items: [
        "Cannot be incorporated for, or later converted into, a Section 8 (non-profit) company",
        "Cannot carry out non-banking financial investment activities",
        "One person cannot be the member of more than one OPC at a time",
        "Automatically must convert to a Private Limited Company if turnover exceeds ₹2 crore or paid-up capital exceeds ₹50 lakh",
      ] },
      { type: "h2", text: "Compliance Load" },
      { type: "p", text: "An OPC's compliance sits between a proprietorship and a full Private Limited Company — annual filing of AOC-4 and MGT-7A is mandatory, along with a statutory audit regardless of turnover, but the requirement for a minimum of two directors and regular board meetings is relaxed for a one-director OPC." },
      { type: "p", text: "For a freelancer or consultant who wants the credibility and liability protection of a registered company without bringing in a co-founder, an OPC is a genuinely good fit — just go in expecting the automatic conversion threshold and plan for it rather than being surprised by it." },
    ],
  },
  {
    slug: "section-8-company-registration-guide",
    title: "Section 8 Company: How to Register a Non-Profit in India",
    excerpt: "The legal structure behind most registered NGOs, foundations, and charitable trusts operating as companies.",
    category: "Company Registration",
    readTime: "6 min read",
    date: "15 Jun 2026",
    image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=900&q=80",
    content: [
      { type: "p", text: "A Section 8 Company (named for the relevant section of the Companies Act, 2013) is India's most credible legal structure for a non-profit that wants a formal, government-recognised entity rather than an informal trust or society." },
      { type: "h2", text: "What Makes It Different" },
      { type: "p", text: "The core rule is simple: profits, if any, must be reinvested into the organisation's stated charitable, educational, religious, or social objectives — not distributed to members as dividends. In exchange, the Central Government grants a licence dropping the words \"Private Limited\" or \"Limited\" from the name, and the structure carries far more credibility with grant-making bodies and CSR-funding corporates than a trust or society registration." },
      { type: "h2", text: "Registration Process" },
      { type: "list", items: [
        "Obtain DSC and DIN for proposed directors",
        "Apply for a Section 8 licence (INC-12) along with SPICe+ incorporation, stating the charitable objects",
        "File MOA and AOA reflecting the non-profit purpose",
        "Receive Certificate of Incorporation along with the Section 8 licence",
      ] },
      { type: "h2", text: "Tax Benefits" },
      { type: "p", text: "A Section 8 Company is not automatically tax-exempt — it must separately apply for 12A registration (income tax exemption) and 80G registration (so donors can claim a tax deduction on their contributions). Without these two registrations, a Section 8 Company pays tax like any other company despite its non-profit objects, which is a step founders frequently miss." },
      { type: "p", text: "Minimum requirement is 2 directors (7 for a public Section 8 Company), no minimum capital, and annual compliance mirrors a Private Limited Company — AOC-4, MGT-7, and statutory audit — plus the additional CSR-1 filing if the entity wishes to receive corporate CSR funding." },
    ],
  },
  {
    slug: "gst-registration-who-needs-it",
    title: "GST Registration: Who Needs It and How to Apply",
    excerpt: "Turnover thresholds, mandatory-registration triggers, and the exact documents GSTN asks for.",
    category: "GST",
    readTime: "6 min read",
    date: "1 Jul 2026",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=900&q=80",
    content: [
      { type: "p", text: "GST registration becomes mandatory once your aggregate turnover crosses ₹40 lakh for goods (₹20 lakh for special-category states) or ₹20 lakh for services (₹10 lakh for special-category states). But turnover isn't the only trigger — several activities require registration regardless of how small your revenue is." },
      { type: "h2", text: "Mandatory Registration Regardless of Turnover" },
      { type: "list", items: [
        "Selling on e-commerce marketplaces like Amazon, Flipkart, or Meesho",
        "Making any inter-state supply of goods",
        "Exporting or importing goods or services",
        "Operating as a casual taxable person or non-resident taxable person",
        "Liable to pay tax under reverse charge",
      ] },
      { type: "h2", text: "Documents Required" },
      { type: "list", items: [
        "PAN of the business/proprietor",
        "Aadhaar of the authorised signatory",
        "Proof of business registration (incorporation certificate, partnership deed, etc.)",
        "Address proof of the principal place of business",
        "Bank account details (cancelled cheque or bank statement)",
        "Digital Signature Certificate (mandatory for companies and LLPs)",
      ] },
      { type: "h2", text: "Timeline" },
      { type: "p", text: "Once the application (Form GST REG-01) is filed with all documents in order, GSTIN is typically issued within 2–7 working days. Applications flagged for physical verification (common for businesses without a clearly documented office address) can take longer." },
      { type: "p", text: "Registering voluntarily below the threshold is also allowed and sometimes worthwhile — it lets you claim input tax credit on purchases and signals legitimacy to B2B customers who prefer dealing with GST-registered vendors." },
    ],
  },
  {
    slug: "gst-return-filing-deadlines",
    title: "GST Return Filing Deadlines You Cannot Afford to Miss",
    excerpt: "GSTR-1, GSTR-3B, and the annual return — a clear month-by-month reference.",
    category: "GST",
    readTime: "5 min read",
    date: "26 Jun 2026",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=900&q=80",
    content: [
      { type: "p", text: "GST return filing runs on a strict monthly or quarterly cycle depending on your turnover and scheme, and missing a deadline triggers both a late fee and interest on any tax due — neither of which is waived easily." },
      { type: "h2", text: "Monthly Filers" },
      { type: "list", items: [
        "GSTR-1 (outward supplies) — due 11th of the following month",
        "GSTR-3B (summary return with tax payment) — due 20th of the following month",
      ] },
      { type: "h2", text: "QRMP Scheme (Turnover Below ₹5 Crore)" },
      { type: "p", text: "Businesses under ₹5 crore turnover can opt for the Quarterly Return, Monthly Payment (QRMP) scheme — filing GSTR-1 and GSTR-3B quarterly while still paying estimated tax monthly via a simple challan. This meaningfully reduces the filing burden without losing input tax credit continuity." },
      { type: "h2", text: "Annual Return" },
      { type: "p", text: "GSTR-9 (annual return) is mandatory for taxpayers with turnover above ₹2 crore, due by 31 December following the financial year. Above ₹5 crore turnover, a reconciliation statement (GSTR-9C, self-certified) is also required." },
      { type: "h2", text: "Late Filing Penalty" },
      { type: "p", text: "The late fee is ₹50 per day (₹25 CGST + ₹25 SGST) for regular returns, capped based on turnover, and ₹20 per day for nil returns. Interest on unpaid tax runs at 18% per annum from the due date — this compounds faster than most business owners expect, which is exactly why a compliance calendar with reminders matters more than most founders assume until they've missed one." },
    ],
  },
  {
    slug: "common-gst-filing-mistakes",
    title: "Common GST Filing Mistakes That Trigger Notices",
    excerpt: "The recurring errors that turn a routine filing into a departmental scrutiny case.",
    category: "GST",
    readTime: "6 min read",
    date: "18 Jun 2026",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=900&q=80",
    content: [
      { type: "p", text: "Most GST notices aren't triggered by deliberate evasion — they come from mismatches that a business could have caught before filing. Here are the ones we see most often in practice." },
      { type: "h2", text: "GSTR-1 vs GSTR-3B Mismatch" },
      { type: "p", text: "If the outward supply figures in your GSTR-1 don't match the summary values reported in GSTR-3B, the system auto-flags the discrepancy. This usually happens when invoices are amended after GSTR-1 is filed but the correction isn't carried through to GSTR-3B in the same period." },
      { type: "h2", text: "Claiming ITC Without GSTR-2B Support" },
      { type: "p", text: "Input tax credit can only be claimed to the extent it appears in your auto-populated GSTR-2B. Claiming credit for an invoice your supplier hasn't uploaded — even if you genuinely paid for the purchase — invites a mismatch notice and potential reversal with interest." },
      { type: "h2", text: "Wrong HSN/SAC Codes" },
      { type: "p", text: "Using an incorrect HSN (goods) or SAC (services) code can misclassify your supply into the wrong tax slab, understating or overstating liability. Businesses above ₹5 crore turnover must report a 6-digit HSN code — a common oversight is continuing to use the 4-digit code after crossing the threshold." },
      { type: "h2", text: "E-Way Bill and E-Invoice Gaps" },
      { type: "p", text: "For businesses above the e-invoicing threshold, an invoice raised without a corresponding IRN (Invoice Reference Number) is technically not a valid tax invoice — this is one of the most common reasons ITC gets denied to the buyer, even though the seller thinks the invoice was properly issued." },
      { type: "p", text: "A monthly reconciliation between your books, GSTR-1, GSTR-2B, and GSTR-3B before filing catches nearly all of these before they become a notice." },
    ],
  },
  {
    slug: "gst-on-services-rates-exemptions",
    title: "GST on Services: Rates, Exemptions and Reverse Charge Explained",
    excerpt: "Why the same service can attract 0%, 5%, 12%, or 18% GST depending on how it's structured.",
    category: "GST",
    readTime: "6 min read",
    date: "10 Jun 2026",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=900&q=80",
    content: [
      { type: "p", text: "Unlike goods, most services in India are taxed at a flat 18% GST — but there are enough exceptions that assuming 18% by default causes real pricing and compliance errors." },
      { type: "h2", text: "Common Service Rate Slabs" },
      { type: "list", items: [
        "18% — Most professional, consulting, IT, and B2B services (the default rate)",
        "12% — Construction of affordable residential property, certain job-work services",
        "5% — Transport services (goods transport agencies, without ITC), restaurant services (non-AC/takeaway categories)",
        "Nil/Exempt — Healthcare services, educational services, certain financial services",
      ] },
      { type: "h2", text: "Reverse Charge Mechanism (RCM)" },
      { type: "p", text: "Under RCM, the recipient of a service pays GST directly to the government instead of the supplier collecting it — this applies to services like legal services from an advocate to a business, services from a Goods Transport Agency, and services received from an unregistered supplier in specified categories. If you're a business receiving such services, you're liable to self-invoice and pay tax under RCM even though your vendor never charged you GST." },
      { type: "h2", text: "Export of Services" },
      { type: "p", text: "Export of services is zero-rated (not exempt) provided payment is received in convertible foreign exchange and the recipient is located outside India — you can either export under a Letter of Undertaking (LUT) without paying IGST, or pay IGST and claim a refund. Most exporters prefer the LUT route since it avoids blocking working capital in a refund claim." },
    ],
  },
  {
    slug: "itr-filing-2026-which-form",
    title: "ITR Filing 2026: Which Form Applies to You",
    excerpt: "ITR-1 through ITR-7 — a plain-language guide to picking the right form the first time.",
    category: "Income Tax",
    readTime: "6 min read",
    date: "3 Jul 2026",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=900&q=80",
    content: [
      { type: "p", text: "Filing the wrong ITR form doesn't just cause a rejection — it can trigger a defective-return notice under Section 139(9), forcing a refile within a tight window. Here's how to pick correctly the first time." },
      { type: "h2", text: "For Individuals" },
      { type: "list", items: [
        "ITR-1 (Sahaj) — Salary/pension income, one house property, other income up to ₹50 lakh total income, no capital gains",
        "ITR-2 — Individuals with capital gains, multiple house properties, or foreign income/assets",
        "ITR-3 — Individuals with business or professional income (not under presumptive taxation)",
        "ITR-4 (Sugam) — Presumptive taxation under Section 44AD/44ADA/44AE, total income up to ₹50 lakh",
      ] },
      { type: "h2", text: "For Businesses" },
      { type: "list", items: [
        "ITR-5 — Partnership firms and LLPs",
        "ITR-6 — Companies (other than those claiming Section 11 exemption)",
        "ITR-7 — Trusts, political parties, and institutions claiming exemption under Sections 11/12/13A/13B",
      ] },
      { type: "h2", text: "A Quick Filter" },
      { type: "p", text: "If you're a salaried individual with no capital gains and no business income, ITR-1 almost always applies. The moment you have capital gains from mutual funds or stocks — even a small amount — you move to ITR-2. Freelancers and consultants filing under presumptive taxation (44ADA) should use ITR-4; if you maintain full books instead, it's ITR-3." },
      { type: "p", text: "When in doubt, filing the more detailed form is safer than the simpler one — a mismatch between reported income sources and the form's scope is one of the most common triggers for a scrutiny notice." },
    ],
  },
  {
    slug: "old-vs-new-tax-regime-comparison",
    title: "Old vs New Tax Regime: A Practical Comparison",
    excerpt: "The new regime isn't automatically better just because it has lower slab rates — here's how to actually decide.",
    category: "Income Tax",
    readTime: "7 min read",
    date: "27 Jun 2026",
    image: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=900&q=80",
    content: [
      { type: "p", text: "Since the new tax regime became the default option, the real decision every taxpayer faces isn't which regime has lower rates on paper — it's whether your deductions are large enough to make the old regime's higher rates still work out cheaper." },
      { type: "h2", text: "What the New Regime Gives Up" },
      { type: "p", text: "The new regime's lower slab rates come at the cost of most common deductions — no Section 80C (ELSS, PPF, life insurance), no HRA exemption, no home loan interest deduction under Section 24(b) for a self-occupied property, and no Chapter VI-A deductions beyond a few exceptions like the employer's NPS contribution." },
      { type: "h2", text: "When the Old Regime Still Wins" },
      { type: "p", text: "If you're paying a home loan on a self-occupied property, claiming HRA, and maxing out 80C investments, the combined deduction can easily cross ₹3–4 lakh — at that level, the old regime's higher slab rates are usually still cheaper in absolute tax paid. Salaried employees with significant HRA and home loan claims are the group most likely to still benefit from the old regime." },
      { type: "h2", text: "When the New Regime Wins" },
      { type: "p", text: "If you don't have a home loan, don't claim HRA (e.g. you own your home or live with family), and don't invest heavily in 80C instruments, the new regime's lower rates plus the standard deduction usually come out ahead with far less paperwork." },
      { type: "p", text: "There's no universal answer — the only reliable way to decide is to actually compute both scenarios against your real numbers, which is exactly what our free Income Tax Calculator does side by side." },
    ],
  },
  {
    slug: "advance-tax-who-pays-how-to-calculate",
    title: "Advance Tax: Who Pays It and How to Calculate",
    excerpt: "Miss an installment and the interest starts compounding — here's the schedule and the calculation.",
    category: "Income Tax",
    readTime: "5 min read",
    date: "22 Jun 2026",
    image: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=900&q=80",
    content: [
      { type: "p", text: "Advance tax applies to anyone whose total tax liability for the year exceeds ₹10,000 after TDS — this covers most freelancers, consultants, and business owners, not just large corporations. Salaried individuals are usually exempt since their employer deducts TDS through the year, unless they have significant additional income." },
      { type: "h2", text: "Payment Schedule" },
      { type: "list", items: [
        "By 15 June — 15% of estimated tax liability",
        "By 15 September — 45% of estimated tax liability (cumulative)",
        "By 15 December — 75% of estimated tax liability (cumulative)",
        "By 15 March — 100% of estimated tax liability (cumulative)",
      ] },
      { type: "h2", text: "Presumptive Taxation Exception" },
      { type: "p", text: "Taxpayers under presumptive taxation (Section 44AD/44ADA) can pay their entire advance tax liability in a single installment by 15 March instead of following the quarterly schedule — a genuine simplification for small businesses and professionals." },
      { type: "h2", text: "Interest for Shortfall" },
      { type: "p", text: "Sections 234B and 234C impose interest at 1% per month for advance tax shortfall and for missing/underpaying an installment respectively. Because this compounds monthly rather than being a one-time penalty, underestimating income early in the year and correcting it only at filing time is one of the more expensive mistakes a growing business can make." },
    ],
  },
  {
    slug: "section-43bh-msme-payment-rule",
    title: "Section 43B(h): The MSME Payment Rule Every Buyer Must Know",
    excerpt: "Pay a registered MSME vendor late, and the expense may become non-deductible in your own tax return.",
    category: "Income Tax",
    readTime: "5 min read",
    date: "14 Jun 2026",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=900&q=80",
    content: [
      { type: "p", text: "Section 43B(h), effective from FY 2023-24, is one of the more consequential recent changes for any business that buys from small vendors — and one of the least understood." },
      { type: "h2", text: "What It Actually Says" },
      { type: "p", text: "If you buy goods or services from a supplier registered as a Micro or Small Enterprise under the MSMED Act, and you don't pay them within the timeline agreed in writing (or 45 days if there's no written agreement), the expense is disallowed for income tax purposes in the year it was incurred — deductible only in the year you actually pay." },
      { type: "h2", text: "Why It Catches Businesses Off Guard" },
      { type: "p", text: "Many buyers don't actually know which of their vendors are MSME-registered, since there's no requirement for a supplier to announce it on every invoice. A business with a habit of 60–90 day payment cycles to vendors can suddenly find a meaningful chunk of expenses disallowed simply because the vendor happened to be Udyam-registered." },
      { type: "h2", text: "What to Do About It" },
      { type: "p", text: "Ask new vendors directly whether they hold Udyam registration, build the 45-day (or agreed) payment window into your accounts-payable process, and reconcile outstanding MSME dues before year-end closing — this single check has become one of the more valuable additions to a standard pre-filing review." },
      { type: "p", text: "Note that this applies only to Micro and Small enterprises — Medium enterprises are excluded from this specific provision, so vendor classification matters, not just Udyam registration status." },
    ],
  },
  {
    slug: "tax-audit-section-44ab-applicability",
    title: "Tax Audit Under Section 44AB: Applicability and Deadlines",
    excerpt: "The ₹1 crore threshold isn't the whole story — the digital-transactions exception changes everything.",
    category: "Income Tax",
    readTime: "5 min read",
    date: "8 Jun 2026",
    image: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=900&q=80",
    content: [
      { type: "p", text: "Tax audit under Section 44AB is mandatory once a business's turnover crosses ₹1 crore — but that threshold jumps to ₹10 crore if over 95% of both receipts and payments happen through banking channels rather than cash." },
      { type: "h2", text: "Who Needs a Tax Audit" },
      { type: "list", items: [
        "Businesses with turnover exceeding ₹1 crore (₹10 crore if cash transactions are under 5%)",
        "Professionals with gross receipts exceeding ₹50 lakh (₹75 lakh under the same digital-transaction condition)",
        "Anyone opting out of presumptive taxation after previously opting in, within the lock-in period",
        "Taxpayers under presumptive taxation whose actual profit is lower than the presumptive rate and total income exceeds the basic exemption limit",
      ] },
      { type: "h2", text: "Deadline" },
      { type: "p", text: "The tax audit report (Form 3CA/3CB and 3CD) must be filed by 30 September of the assessment year for most taxpayers, with the ITR itself due by 31 October where a tax audit applies. Missing the audit deadline attracts a penalty under Section 271B — the lower of 0.5% of turnover or ₹1.5 lakh." },
      { type: "h2", text: "A Practical Note" },
      { type: "p", text: "Businesses hovering near the ₹1 crore mark should track their cash-vs-digital transaction ratio through the year, not just at closing — crossing into tax-audit territory unexpectedly, with no CA engaged and no books finalised in time, is a far more common problem than the audit itself." },
    ],
  },
  {
    slug: "tds-on-professional-fees-194j",
    title: "TDS on Professional Fees: Section 194J Explained",
    excerpt: "10% or 2%? The rate depends on exactly what kind of service was rendered.",
    category: "TDS",
    readTime: "5 min read",
    date: "5 Jul 2026",
    image: "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?w=900&q=80",
    content: [
      { type: "p", text: "Section 194J requires TDS deduction on payments for professional or technical services once the payment (or aggregate payments in a year) exceeds ₹30,000 to a single payee — but the rate you deduct depends on which category the payment falls into." },
      { type: "h2", text: "Rate Breakdown" },
      { type: "list", items: [
        "10% — Professional services (legal, medical, engineering, architectural, accountancy, technical consultancy, interior decoration)",
        "2% — Technical services (fees for technical services, not professional services), and payments to a call-centre operator",
        "2% — Royalty for sale, distribution, or exhibition of cinematographic films",
      ] },
      { type: "h2", text: "The Distinction That Trips People Up" },
      { type: "p", text: "\"Professional services\" and \"technical services\" sound interchangeable but aren't — a CA's audit fee is professional services (10%), while an IT company's software maintenance contract is often treated as technical services (2%). Getting this wrong means either under-deducting (making the deductor liable for the shortfall plus interest) or over-deducting (creating an unnecessary refund claim for the payee)." },
      { type: "h2", text: "Threshold and Exemptions" },
      { type: "p", text: "The ₹30,000 threshold applies separately to each category — professional and technical services are counted independently, so a payee could receive up to ₹30,000 under each head in a year before TDS kicks in on either. Individuals and HUFs not subject to tax audit in the preceding year are generally not required to deduct TDS under this section." },
    ],
  },
  {
    slug: "tds-return-filing-24q-26q",
    title: "TDS Return Filing: Forms 24Q, 26Q, and Due Dates",
    excerpt: "Deducting TDS is only half the job — filing the return correctly is what keeps the deductee's credit intact.",
    category: "TDS",
    readTime: "5 min read",
    date: "28 May 2026",
    image: "https://images.unsplash.com/photo-1543286386-713bdd548da4?w=900&q=80",
    content: [
      { type: "p", text: "Every business that deducts TDS must file a quarterly return, and picking the wrong form is one of the most common — and most disruptive — errors we see, since it directly affects whether the deductee can claim credit for tax already deducted from their payment." },
      { type: "h2", text: "Which Form to Use" },
      { type: "list", items: [
        "Form 24Q — TDS deducted on salary payments",
        "Form 26Q — TDS deducted on all other domestic payments (professional fees, rent, contractor payments, interest)",
        "Form 27Q — TDS deducted on payments to non-residents",
      ] },
      { type: "h2", text: "Quarterly Due Dates" },
      { type: "list", items: [
        "Q1 (Apr–Jun) — due 31 July",
        "Q2 (Jul–Sep) — due 31 October",
        "Q3 (Oct–Dec) — due 31 January",
        "Q4 (Jan–Mar) — due 31 May",
      ] },
      { type: "h2", text: "Penalties for Delay" },
      { type: "p", text: "Late filing attracts a fee of ₹200 per day under Section 234E until the return is filed, capped at the TDS amount itself. Separately, a penalty of ₹10,000 to ₹1,00,000 can be levied under Section 271H for incorrect or delayed filing — and until the return is filed correctly, the deductee cannot see the credit reflected in their Form 26AS, which routinely causes friction with vendors and employees asking why their tax credit isn't showing up." },
    ],
  },
  {
    slug: "annual-roc-filing-checklist",
    title: "Annual ROC Filing Checklist for Private Limited Companies",
    excerpt: "AOC-4, MGT-7, DIR-3 KYC, and ADT-1 — the four filings every Pvt Ltd company owes the ROC each year.",
    category: "Compliance",
    readTime: "6 min read",
    date: "30 Jun 2026",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=900&q=80",
    content: [
      { type: "p", text: "Annual ROC compliance is where most first-time founders underestimate the ongoing obligation of running a Private Limited Company — incorporation is a one-time event, but these filings recur every single year regardless of whether the company did any business." },
      { type: "h2", text: "The Four Core Filings" },
      { type: "list", items: [
        "AOC-4 — Filing of financial statements, due within 30 days of the AGM",
        "MGT-7/MGT-7A — Annual return, due within 60 days of the AGM",
        "ADT-1 — Auditor appointment/reappointment intimation, due within 15 days of the AGM",
        "DIR-3 KYC — Annual KYC for every director holding a DIN, due by 30 September",
      ] },
      { type: "h2", text: "AGM Timing" },
      { type: "p", text: "The Annual General Meeting must be held within 6 months of the financial year-end (so by 30 September for a company following the standard April–March year), and every subsequent filing deadline above is calculated from the actual AGM date — delaying the AGM delays everything downstream." },
      { type: "h2", text: "Penalties for Missing a Filing" },
      { type: "p", text: "The additional fee for late ROC filings is steep and non-negotiable: ₹100 per day of delay per form, with no upper cap — a filing that's 100 days late costs ₹10,000 in additional fees alone, on top of the base filing fee. Repeated non-compliance can also lead to the company being marked for Strike Off." },
      { type: "p", text: "A simple compliance calendar mapped to your specific AGM date, reviewed quarterly, is the single most effective way to avoid these entirely preventable penalties." },
    ],
  },
  {
    slug: "director-kyc-dir3-deadline-penalty",
    title: "Director KYC (DIR-3 KYC): Deadline and Penalty for Missing It",
    excerpt: "A ₹5,000 penalty and a deactivated DIN — for a filing that takes ten minutes.",
    category: "Compliance",
    readTime: "4 min read",
    date: "16 Jun 2026",
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=900&q=80",
    content: [
      { type: "p", text: "Every individual holding a Director Identification Number (DIN) — active or not currently serving as a director — must file DIR-3 KYC annually, by 30 September, to keep that DIN active." },
      { type: "h2", text: "Who Must File" },
      { type: "p", text: "Anyone allotted a DIN on or before 31 March of the financial year, whose DIN status is \"Approved\", must file — including individuals who obtained a DIN but never actually served as a director on any company's board. This surprises a lot of people who assume the obligation ends if they're no longer active." },
      { type: "h2", text: "Web vs eForm Filing" },
      { type: "p", text: "If none of your KYC details (mobile, email, address) have changed since the last filing, you can use the simpler DIR-3 KYC-WEB service (just an OTP verification). If any detail has changed, you must file the full DIR-3 KYC eForm with supporting documents and a practising professional's certification." },
      { type: "h2", text: "The Cost of Missing the Deadline" },
      { type: "p", text: "Miss 30 September, and the DIN is marked \"Deactivated due to non-filing of DIR-3 KYC\" the very next day. Reactivating it requires filing the KYC form along with a flat ₹5,000 penalty — regardless of how many days late you are. A deactivated DIN also means that individual cannot be validly appointed or continue as a director on any company's board until it's reactivated, which can hold up unrelated corporate actions like a board resolution or a new appointment." },
    ],
  },
  {
    slug: "consequences-of-not-filing-annual-returns",
    title: "What Happens If You Don't File Annual Returns",
    excerpt: "It doesn't stop at a late fee — director disqualification and Strike Off are the real endgame.",
    category: "Compliance",
    readTime: "5 min read",
    date: "9 Jun 2026",
    image: "https://images.unsplash.com/photo-1521898284481-a5ec348cb555?w=900&q=80",
    content: [
      { type: "p", text: "A surprising number of dormant or low-activity companies simply stop filing annual returns, assuming that since there's no business activity, there's nothing to report. That assumption is wrong, and the consequences escalate in a fairly predictable sequence." },
      { type: "h2", text: "Stage 1 — Additional Fees" },
      { type: "p", text: "The ₹100/day additional fee (per form, uncapped) starts accruing immediately after the due date. This alone can turn a routine filing into a five-figure expense within a few months of neglect." },
      { type: "h2", text: "Stage 2 — Director Disqualification" },
      { type: "p", text: "Under Section 164(2) of the Companies Act, a director of a company that has failed to file financial statements or annual returns for three consecutive financial years becomes disqualified from being reappointed as a director in that company or appointed as a director in any other company for five years." },
      { type: "h2", text: "Stage 3 — Strike Off by the ROC" },
      { type: "p", text: "The Registrar of Companies can suo-motu strike off a company that hasn't been carrying on business or hasn't filed returns for two consecutive financial years — removing it from the register entirely. Reviving a struck-off company requires an application to the National Company Law Tribunal (NCLT), which is considerably more expensive and time-consuming than simply staying compliant." },
      { type: "p", text: "If a company genuinely has no operations, the cleaner and cheaper path is a voluntary Strike Off (Form STK-2) rather than letting non-filing accumulate into director disqualification." },
    ],
  },
  {
    slug: "trademark-registration-step-by-step",
    title: "Trademark Registration in India: A Step-by-Step Guide",
    excerpt: "From search to certificate — the real timeline is 18–24 months, and here's why.",
    category: "Trademark",
    readTime: "7 min read",
    date: "29 Jun 2026",
    image: "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=900&q=80",
    content: [
      { type: "p", text: "Trademark registration protects your brand name, logo, or slogan — but the process is considerably longer than most founders expect, and understanding the stages helps set realistic expectations rather than assuming something's gone wrong at month six." },
      { type: "h2", text: "Step 1 — Search" },
      { type: "p", text: "Before filing, search the IP India public trademark database (or use our free Trademark Class Finder to identify the right NICE class first) to check whether an identical or confusingly similar mark already exists in your class." },
      { type: "h2", text: "Step 2 — Filing (TM-A)" },
      { type: "p", text: "You can use the ™ symbol immediately after filing your application — it does not require registration to be granted first. The application is examined by the Trademark Registry, typically within 6–12 months of filing." },
      { type: "h2", text: "Step 3 — Examination and Publication" },
      { type: "p", text: "If the examiner raises no objection (or objections are successfully overcome), the mark is published in the Trademark Journal for four months, during which anyone can file an opposition." },
      { type: "h2", text: "Step 4 — Registration" },
      { type: "p", text: "If no opposition is filed (or an opposition is successfully defended), the Registry issues the registration certificate. You can only use the ® symbol after this certificate is issued — using it before registration is a legal misrepresentation." },
      { type: "h2", text: "Realistic Timeline and Validity" },
      { type: "p", text: "End to end, expect 18–24 months for an uncontested application. Once registered, protection lasts 10 years and is renewable indefinitely in further 10-year terms — making it one of the few IP protections that, in principle, never has to expire." },
    ],
  },
  {
    slug: "trademark-classes-explained",
    title: "Trademark Classes Explained: Choosing the Right One",
    excerpt: "45 classes, and registering in the wrong one leaves your actual business unprotected.",
    category: "Trademark",
    readTime: "5 min read",
    date: "19 Jun 2026",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=900&q=80",
    content: [
      { type: "p", text: "Trademark protection in India is class-specific — registering your brand name in Class 25 (clothing) does nothing to stop someone else from using the identical name in Class 42 (software services). Picking the right class, or classes, is as important as the registration itself." },
      { type: "h2", text: "Goods vs Services" },
      { type: "p", text: "Classes 1 through 34 cover physical goods — everything from chemicals (Class 1) to cosmetics (Class 3) to clothing (Class 25) to beverages (Classes 32–33). Classes 35 through 45 cover services — advertising and business (35), finance and insurance (36), education and entertainment (41), IT and scientific services (42), and legal services (45)." },
      { type: "h2", text: "Multi-Class Businesses" },
      { type: "p", text: "A business that both manufactures a product and sells it under its own brand — say, a packaged food company that also runs a chain of cafes — genuinely needs registration in more than one class (e.g. Class 29/30 for the food products and Class 43 for restaurant services). Each additional class is filed and examined separately, with its own government fee." },
      { type: "h2", text: "Why Getting This Wrong Is Expensive" },
      { type: "p", text: "Filing in the wrong class doesn't just waste the government fee — it can mean discovering, a year later when a competitor uses your name in your actual line of business, that your registration offers zero protection where you actually needed it. Getting professional input on class selection before filing is far cheaper than re-filing after a rejection or a real infringement dispute." },
    ],
  },
  {
    slug: "what-to-do-trademark-objection",
    title: "What to Do When You Receive a Trademark Objection",
    excerpt: "An objection is not a rejection — but the one-month response window is unforgiving.",
    category: "Trademark",
    readTime: "5 min read",
    date: "11 Jun 2026",
    image: "https://images.unsplash.com/photo-1605902711622-cfb43c4437b5?w=900&q=80",
    content: [
      { type: "p", text: "Receiving an examination report with an objection feels alarming, but it's a routine part of the process — a large share of trademark applications get at least one objection before registration. What matters is responding correctly and within the deadline." },
      { type: "h2", text: "Common Objection Grounds" },
      { type: "list", items: [
        "The mark is descriptive of the goods/services rather than distinctive (Section 9)",
        "The mark is similar to an existing registered or pending trademark (Section 11)",
        "Incomplete or incorrect Power of Attorney (TM-48) or user-affidavit documentation",
        "Vague or overly broad specification of goods/services",
      ] },
      { type: "h2", text: "The Response Window" },
      { type: "p", text: "You have 30 days from the date of the examination report to file a response — missing this deadline results in the application being treated as abandoned, requiring a fresh filing (and a fresh set of fees) rather than a revival." },
      { type: "h2", text: "How a Response Is Built" },
      { type: "p", text: "A strong response typically combines a legal argument (why the mark is in fact distinctive, or why it's sufficiently different from the cited conflicting mark) with evidence of prior use — invoices, advertising material, or sales records showing you've been using the mark in commerce, which can support a claim to distinctiveness acquired through use even for an otherwise descriptive mark." },
      { type: "p", text: "If the response doesn't resolve the objection, the next stage is a show-cause hearing before the Registrar — at which point professional representation genuinely matters, since the arguments are legal, not just procedural." },
    ],
  },
  {
    slug: "msme-registration-benefits",
    title: "MSME Registration Benefits Every Small Business Should Know",
    excerpt: "Free, fast, and more consequential than most founders realise — including the payment-protection rule.",
    category: "MSME & Startup",
    readTime: "5 min read",
    date: "25 Jun 2026",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=900&q=80",
    content: [
      { type: "p", text: "MSME (Udyam) registration is one of the few genuinely free, same-day government registrations available to Indian businesses — and its benefits go well beyond the collateral-free-loan headline most people know about." },
      { type: "h2", text: "Classification" },
      { type: "list", items: [
        "Micro — investment up to ₹2.5 crore and turnover up to ₹10 crore",
        "Small — investment up to ₹25 crore and turnover up to ₹100 crore",
        "Medium — investment up to ₹125 crore and turnover up to ₹500 crore",
      ] },
      { type: "h2", text: "The Benefit Most Businesses Miss" },
      { type: "p", text: "Buyers of goods or services from a registered Micro or Small Enterprise must pay within the agreed period, or 45 days if there's no written agreement — and delayed payment automatically accrues compound interest at three times the RBI's notified bank rate. This is enforced through Section 43B(h) of the Income Tax Act, which disallows the buyer's expense deduction for late payments. In practice, this has made larger buyers noticeably more careful about paying small vendors on time." },
      { type: "h2", text: "Other Concrete Benefits" },
      { type: "list", items: [
        "Priority sector lending status with banks, often at lower interest rates",
        "Reduced trademark filing fee (₹4,500 vs ₹9,000 per class for others)",
        "Reservation and price preference in specific government tenders",
        "Protection against delayed payments with statutory interest, as above",
        "Eligibility for various state and central subsidy schemes",
      ] },
      { type: "p", text: "Registration is done entirely online via self-declaration on the Udyam portal, using your Aadhaar and PAN — no documents need to be uploaded, and the certificate is generated immediately." },
    ],
  },
  {
    slug: "startup-india-dpiit-recognition",
    title: "Startup India (DPIIT) Recognition: Eligibility and Tax Benefits",
    excerpt: "A 3-year tax holiday and capital gains exemption — if your startup actually qualifies.",
    category: "MSME & Startup",
    readTime: "6 min read",
    date: "13 Jun 2026",
    image: "https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=900&q=80",
    content: [
      { type: "p", text: "DPIIT (Department for Promotion of Industry and Internal Trade) recognition under Startup India unlocks real tax benefits — but the eligibility criteria are stricter than the marketing suggests, and many companies calling themselves \"startups\" don't actually qualify." },
      { type: "h2", text: "Eligibility Criteria" },
      { type: "list", items: [
        "Incorporated as a Private Limited Company, LLP, or Registered Partnership Firm",
        "Less than 10 years old from the date of incorporation",
        "Annual turnover has not exceeded ₹100 crore in any financial year since incorporation",
        "Working towards innovation, development, or improvement of products/services, or a scalable business model with high potential for employment/wealth creation",
        "Not formed by splitting up or reconstructing an existing business",
      ] },
      { type: "h2", text: "Tax Benefits Once Recognised" },
      { type: "list", items: [
        "Section 80-IAC — 100% profit deduction for any 3 consecutive years out of the first 10 years since incorporation",
        "Section 56 (Angel Tax) exemption on share premium received from resident investors, subject to conditions",
        "Capital gains exemption under Section 54GB when investing sale proceeds of a residential property into eligible startup shares",
      ] },
      { type: "h2", text: "The Application Process" },
      { type: "p", text: "Recognition is applied for online through the Startup India portal, requiring a brief write-up on how the business is innovative and a certificate of incorporation. Approval is not automatic — the DPIIT reviews each application against the innovation/scalability criteria, and a generic services business without a clear innovative angle can genuinely be rejected." },
      { type: "p", text: "It's worth noting: DPIIT recognition and the 80-IAC tax exemption require separate applications — recognition alone does not automatically grant the tax holiday." },
    ],
  },
  {
    slug: "pf-esi-registration-when-mandatory",
    title: "PF and ESI Registration: When Are They Mandatory?",
    excerpt: "The employee-count thresholds that trigger two of the most commonly missed labour-law registrations.",
    category: "Payroll & Labour",
    readTime: "5 min read",
    date: "21 Jun 2026",
    image: "https://images.unsplash.com/photo-1618044733300-9472054094ee?w=900&q=80",
    content: [
      { type: "p", text: "Both PF and ESI registration are triggered by employee headcount, not revenue — which means a small, low-turnover business with enough staff can be non-compliant without ever realising the obligation kicked in." },
      { type: "h2", text: "Provident Fund (PF/EPFO)" },
      { type: "p", text: "PF registration becomes mandatory once an establishment employs 20 or more people. Both employer and employee contribute 12% of basic wages (plus dearness allowance) to the fund. Establishments with fewer than 20 employees can register voluntarily, which is sometimes worthwhile as a retention/benefits tool even before it's legally required." },
      { type: "h2", text: "Employees' State Insurance (ESI)" },
      { type: "p", text: "ESI registration is mandatory once an establishment employs 10 or more people (in most states), covering employees earning up to ₹21,000 per month in gross wages. It provides medical, sickness, maternity, and disablement benefits. The contribution rate is 3.25% from the employer and 0.75% from the employee, calculated on gross wages." },
      { type: "h2", text: "Why Businesses Get Caught Off Guard" },
      { type: "p", text: "Headcount for these thresholds typically includes contract and temporary workers at the establishment, not just permanent payroll employees — a business that has scaled up with a mix of full-time and contract staff can cross the ESI threshold of 10 without a single new \"employee\" being formally hired. Non-compliance carries both interest on unpaid contributions and, in serious cases, prosecution — reviewing actual headcount against these thresholds quarterly is a cheap habit that avoids an expensive surprise." },
    ],
  },
  {
    slug: "payroll-compliance-checklist",
    title: "Payroll Compliance Checklist for Growing Businesses",
    excerpt: "PF, ESI, professional tax, and TDS on salary — the four recurring obligations payroll actually creates.",
    category: "Payroll & Labour",
    readTime: "5 min read",
    date: "6 Jun 2026",
    image: "https://images.unsplash.com/photo-1611095973763-414019e72400?w=900&q=80",
    content: [
      { type: "p", text: "The moment a business hires its first employee, payroll stops being a spreadsheet exercise and becomes a compliance obligation with several moving parts, each on its own deadline." },
      { type: "h2", text: "Monthly Obligations" },
      { type: "list", items: [
        "TDS on salary (Section 192) — deducted based on the employee's declared investments/regime, deposited by the 7th of the following month",
        "PF contribution (if applicable) — deposited by the 15th of the following month via ECR filing",
        "ESI contribution (if applicable) — deposited by the 15th of the following month",
        "Professional tax — deducted and deposited per the applicable state's schedule (rates and due dates vary by state)",
      ] },
      { type: "h2", text: "Annual Obligations" },
      { type: "list", items: [
        "Form 16 issuance to employees, by 15 June following the financial year",
        "Form 24Q (TDS return for salary) filed quarterly",
        "Bonus payment under the Payment of Bonus Act, where applicable, and gratuity provisioning for eligible employees",
      ] },
      { type: "h2", text: "The Real-World Complication" },
      { type: "p", text: "State-specific professional tax rules are the most common source of payroll errors for businesses operating across multiple states — rates, slabs, and even the concept of a registration certificate versus an enrolment certificate differ meaningfully between, say, Maharashtra, Karnataka, and West Bengal. A business hiring its first employee in a new state should treat professional tax as a fresh compliance item to research, not an extension of what worked in the home state." },
    ],
  },
  {
    slug: "virtual-cfo-when-does-your-business-need-one",
    title: "Virtual CFO Services: When Does Your Business Need One?",
    excerpt: "Somewhere between a bookkeeper and a full-time CFO hire, there's a real gap most growing SMEs fall into.",
    category: "Business Advisory",
    readTime: "6 min read",
    date: "23 Jun 2026",
    image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=900&q=80",
    content: [
      { type: "p", text: "Most SMEs cross a threshold — usually somewhere around ₹5 crore in turnover, or the moment they start talking to investors — where basic bookkeeping is no longer enough, but a full-time in-house CFO isn't yet justified on cost. That gap is exactly what virtual CFO services are built for." },
      { type: "h2", text: "What a Virtual CFO Actually Does" },
      { type: "list", items: [
        "Monthly MIS reporting — P&L, balance sheet, and cash flow presented in a form a bank or investor actually wants to see",
        "Cash flow forecasting and working capital management",
        "Investor-ready financial structuring and due-diligence preparation",
        "Tax planning integrated with business decisions, not just year-end compliance",
        "Budgeting, variance analysis, and cost-control recommendations",
      ] },
      { type: "h2", text: "Signs You Need One" },
      { type: "list", items: [
        "You genuinely don't know your monthly burn rate or runway without asking someone",
        "Lenders or investors are asking for financials in a format your current bookkeeping can't produce",
        "You're making pricing or hiring decisions without knowing their real margin impact",
        "Tax planning happens reactively in March instead of proactively through the year",
      ] },
      { type: "h2", text: "Cost vs a Full-Time Hire" },
      { type: "p", text: "A qualified full-time CFO in India typically commands ₹25–40 lakh+ annually, plus benefits — a cost most businesses under ₹10–15 crore turnover can't justify for a role they need part-time attention from. Virtual CFO retainers deliver senior-level financial oversight at a fraction of that cost, scaling up in engagement as the business grows, rather than committing to a full-time salary before the need is fully there." },
    ],
  },
  {
    slug: "converting-proprietorship-to-private-limited",
    title: "How to Convert a Proprietorship into a Private Limited Company",
    excerpt: "The tax-neutral route most growing sole proprietors don't know exists.",
    category: "Business Advisory",
    readTime: "6 min read",
    date: "17 Jun 2026",
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=900&q=80",
    content: [
      { type: "p", text: "A sole proprietorship that's outgrown its structure — usually because a bank or investor wants to see a company, or because personal liability has become a real concern — can convert into a Private Limited Company without dissolving the business or losing continuity." },
      { type: "h2", text: "How the Conversion Works" },
      { type: "p", text: "The proprietor incorporates a new Private Limited Company (via standard SPICe+ registration) and then transfers the proprietorship's business — assets, liabilities, contracts, and employees — into the company via a business transfer/slump sale agreement, in exchange for shares in the new company (a \"slump sale for consideration in shares\" structure)." },
      { type: "h2", text: "Tax Treatment" },
      { type: "p", text: "Under Section 47(xiv) of the Income Tax Act, this conversion can be structured to be tax-neutral — no capital gains tax on the transfer of assets — provided specific conditions are met: all assets and liabilities of the proprietorship become assets and liabilities of the company, the proprietor holds at least 50% of the company's shares for at least 5 years after conversion, and the proprietor receives no consideration other than shares in the company." },
      { type: "h2", text: "What Doesn't Carry Over Automatically" },
      { type: "p", text: "GST registration, licenses (FSSAI, trade license, etc.), and bank accounts do not automatically transfer to the new entity — each must be freshly obtained or transferred in the company's name, which is often the most time-consuming part of the entire conversion, more than the incorporation itself." },
      { type: "p", text: "Carried-forward business losses under the proprietorship also do not automatically transfer to the new company — this is one of the more consequential details that's worth planning around before, not after, the conversion." },
    ],
  },
  {
    slug: "india-compliance-calendar-2026",
    title: "India Compliance Calendar 2026: Key Deadlines for Businesses",
    excerpt: "GST, TDS, ROC, and income tax deadlines mapped onto a single yearly calendar.",
    category: "Compliance",
    readTime: "6 min read",
    date: "4 Jul 2026",
    image: "https://images.unsplash.com/photo-1552581234-26160f608093?w=900&q=80",
    content: [
      { type: "p", text: "Most compliance failures aren't caused by not knowing the rule — they're caused by a deadline arriving unnoticed among a dozen other recurring obligations. A single calendar view makes the pattern easier to plan around." },
      { type: "h2", text: "Monthly, Every Month" },
      { type: "list", items: [
        "7th — TDS/TCS deposit for the previous month",
        "11th — GSTR-1 (monthly filers)",
        "15th — PF and ESI contribution deposit",
        "20th — GSTR-3B (monthly filers)",
      ] },
      { type: "h2", text: "Quarterly" },
      { type: "list", items: [
        "TDS returns (24Q/26Q/27Q) — 31 Jul, 31 Oct, 31 Jan, 31 May",
        "GSTR-1 and GSTR-3B for QRMP-scheme taxpayers",
        "Advance tax installments — 15 Jun, 15 Sep, 15 Dec, 15 Mar",
      ] },
      { type: "h2", text: "Annual, Fixed Dates" },
      { type: "list", items: [
        "30 September — Tax audit report filing, DIR-3 KYC for directors",
        "31 October — ITR filing where tax audit applies",
        "31 December — GSTR-9 annual return, and the general (non-audit) ITR due date in recent years",
        "AOC-4/MGT-7 — Within 30/60 days of the AGM (AGM itself due within 6 months of financial year-end)",
      ] },
      { type: "p", text: "Because several of these deadlines (AOC-4, MGT-7, ADT-1) are calculated relative to your own company's AGM date rather than a fixed calendar date, a generic calendar only gets you most of the way — the last step is always mapping these against your specific entity's actual filing history." },
    ],
  },
  {
    slug: "gst-vs-income-tax-dual-system",
    title: "GST vs Income Tax: Understanding India's Dual Tax System",
    excerpt: "Two entirely different taxes, two different departments, two different filing cycles — often confused as one system.",
    category: "GST",
    readTime: "5 min read",
    date: "31 May 2026",
    image: "https://images.unsplash.com/photo-1556157382-97eda2d62296?w=900&q=80",
    content: [
      { type: "p", text: "New business owners frequently conflate GST and income tax as \"the tax I have to pay,\" but they're structurally unrelated taxes, administered by different authorities, taxing entirely different things." },
      { type: "h2", text: "What Each Tax Actually Taxes" },
      { type: "p", text: "GST is an indirect tax on the supply of goods and services — it's collected from the customer and passed through to the government, and in principle doesn't cost the business anything if input tax credit flows correctly. Income tax is a direct tax on the business's actual profit — what's left after all expenses, and it's a real cost to the business, not a pass-through." },
      { type: "h2", text: "Different Filing Cycles, Different Departments" },
      { type: "p", text: "GST is administered by the GST Network under the GST Council (a joint Centre-State body) and filed monthly or quarterly. Income tax is administered by the Central Board of Direct Taxes (CBDT) through the Income Tax Department and filed annually. A business can be perfectly compliant on one and seriously behind on the other — they don't automatically cross-check each other in real time, though data-sharing between the two systems has increased significantly in recent years." },
      { type: "h2", text: "Why This Distinction Matters Practically" },
      { type: "p", text: "A business can show healthy GST turnover (meaning strong sales) while still reporting a loss for income tax purposes (meaning expenses exceeded revenue) — these are not contradictory, but a mismatch between GST turnover and income-tax-reported revenue, if unexplained, is exactly the kind of red flag that draws scrutiny from both departments independently." },
    ],
  },
];

export const BLOG_CATEGORIES = Array.from(new Set(BLOG_POSTS.map((p) => p.category)));
