export const COMPANY = {
  name: "Company Avenue Advisory",
  fullName: "Company Avenue Advisory Pvt. Ltd.",
  tagline: "Trusted Business Compliance Partner",
  email: "info@companyavenue.in",
  phone: "+91 98765 43210",
  whatsapp: "+919876543210",
  address: "123, Business Hub, Connaught Place, New Delhi – 110001",
  workingHours: "Mon – Sat: 9:00 AM – 7:00 PM",
  website: "https://companyavenue.in",
  gstin: "07AABCC1234D1Z5",
  founded: "2009",
};

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  {
    label: "Services",
    href: "/services",
    children: [
      {
        group: "Company Formation",
        items: [
          { label: "Private Limited Company", href: "/services/private-limited-company" },
          { label: "Limited Liability Partnership", href: "/services/llp-registration" },
          { label: "One Person Company", href: "/services/one-person-company" },
          { label: "Partnership Firm", href: "/services/partnership-firm" },
          { label: "Sole Proprietorship", href: "/services/sole-proprietorship" },
          { label: "Section 8 (NGO) Company", href: "/services/section-8-company" },
          { label: "Nidhi Company", href: "/services/nidhi-company" },
          { label: "Producer Company", href: "/services/producer-company" },
          { label: "Indian Subsidiary", href: "/services/indian-subsidiary" },
          { label: "Branch / Liaison Office", href: "/services/branch-office" },
        ],
      },
      {
        group: "Tax & GST",
        items: [
          { label: "GST Registration", href: "/services/gst-registration" },
          { label: "GST Return Filing", href: "/services/gst-filing" },
          { label: "GST Amendment / Cancellation", href: "/services/gst-amendment" },
          { label: "Income Tax Return", href: "/services/income-tax-return" },
          { label: "TDS Return Filing", href: "/services/tds-return" },
          { label: "Advance Tax Payment", href: "/services/advance-tax" },
          { label: "Tax Audit (Sec 44AB)", href: "/services/tax-audit" },
          { label: "Transfer Pricing Study", href: "/services/transfer-pricing" },
        ],
      },
      {
        group: "MCA / ROC Compliance",
        items: [
          { label: "ROC Annual Filing (Pvt Ltd)", href: "/services/roc-compliance" },
          { label: "LLP Annual Filing", href: "/services/llp-annual-filing" },
          { label: "Director KYC (DIR-3)", href: "/services/director-kyc" },
          { label: "Change in Directors", href: "/services/change-in-directors" },
          { label: "Increase Authorised Capital", href: "/services/increase-authorised-capital" },
          { label: "Registered Office Change", href: "/services/registered-office-change" },
          { label: "Company Name Change", href: "/services/company-name-change" },
          { label: "Strike Off / Company Closure", href: "/services/company-closure" },
        ],
      },
      {
        group: "Startup & MSME",
        items: [
          { label: "Startup India (DPIIT)", href: "/services/startup-india" },
          { label: "MSME / Udyam Registration", href: "/services/msme-registration" },
          { label: "IEC Registration", href: "/services/iec-registration" },
          { label: "FSSAI Food License", href: "/services/fssai-license" },
          { label: "Professional Tax Registration", href: "/services/professional-tax" },
          { label: "Trade License", href: "/services/trade-license" },
          { label: "Drug License", href: "/services/drug-license" },
          { label: "PSARA License", href: "/services/psara-license" },
          { label: "LMPC Registration", href: "/services/lmpc-registration" },
        ],
      },
      {
        group: "Intellectual Property",
        items: [
          { label: "Trademark Registration", href: "/services/trademark-registration" },
          { label: "Trademark Objection Reply", href: "/services/trademark-objection" },
          { label: "Trademark Renewal", href: "/services/trademark-renewal" },
          { label: "Copyright Registration", href: "/services/copyright-registration" },
          { label: "Patent Registration", href: "/services/patent-registration" },
          { label: "Design Registration", href: "/services/design-registration" },
        ],
      },
      {
        group: "Payroll & HR",
        items: [
          { label: "PF Registration & Filing", href: "/services/pf-registration" },
          { label: "ESIC Registration", href: "/services/esic-registration" },
          { label: "Payroll Management", href: "/services/payroll-management" },
          { label: "Gratuity Trust Registration", href: "/services/gratuity-trust" },
        ],
      },
      {
        group: "Accounting & Finance",
        items: [
          { label: "Accounting & Bookkeeping", href: "/services/accounting-bookkeeping" },
          { label: "Virtual CFO Services", href: "/services/virtual-cfo" },
          { label: "Business Valuation", href: "/services/business-valuation" },
          { label: "Financial Statements", href: "/services/financial-statements" },
        ],
      },
    ],
  },
  {
    label: "Industries",
    href: "/industries",
    children: [
      {
        group: "Sectors",
        items: [
          { label: "IT & Technology", href: "/industries/it-technology" },
          { label: "Manufacturing", href: "/industries/manufacturing" },
          { label: "Healthcare", href: "/industries/healthcare" },
          { label: "Retail & Ecommerce", href: "/industries/retail-ecommerce" },
          { label: "Import & Export", href: "/industries/import-export" },
          { label: "Real Estate", href: "/industries/real-estate" },
        ],
      },
    ],
  },
  { label: "Resources", href: "/resources" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const SERVICES = [
  // ── Company Formation ──────────────────────────────────────────────
  {
    id: "private-limited-company",
    title: "Private Limited Company",
    shortDesc: "Incorporate your Pvt. Ltd. company with end-to-end support and fast government processing.",
    icon: "Building2",
    category: "Company Formation",
    popular: true,
  },
  {
    id: "llp-registration",
    title: "LLP Registration",
    shortDesc: "Register a Limited Liability Partnership with flexible structure and lower compliance burden.",
    icon: "Users",
    category: "Company Formation",
  },
  {
    id: "one-person-company",
    title: "One Person Company",
    shortDesc: "Start your solo business journey with complete limited liability protection.",
    icon: "User",
    category: "Company Formation",
  },
  {
    id: "partnership-firm",
    title: "Partnership Firm Registration",
    shortDesc: "Register a traditional partnership firm with a deed — ideal for small businesses run by 2–20 partners.",
    icon: "Handshake",
    category: "Company Formation",
  },
  {
    id: "sole-proprietorship",
    title: "Sole Proprietorship",
    shortDesc: "Set up a sole proprietorship with GST, bank account and business identity — simplest business form.",
    icon: "PersonStanding",
    category: "Company Formation",
  },
  {
    id: "section-8-company",
    title: "Section 8 Company (NGO)",
    shortDesc: "Register a non-profit company for charitable, educational, or social objectives under Section 8.",
    icon: "Heart",
    category: "Company Formation",
  },
  {
    id: "nidhi-company",
    title: "Nidhi Company Registration",
    shortDesc: "Register a Nidhi Company to promote savings and lending among members — RBI-governed.",
    icon: "PiggyBank",
    category: "Company Formation",
  },
  {
    id: "producer-company",
    title: "Producer Company Registration",
    shortDesc: "Incorporate a Producer Company for farmers, artisans and primary producers with cooperative benefits.",
    icon: "Sprout",
    category: "Company Formation",
  },
  {
    id: "indian-subsidiary",
    title: "Indian Subsidiary of Foreign Company",
    shortDesc: "Set up a 100% foreign-owned Indian subsidiary under FEMA and Companies Act regulations.",
    icon: "Globe",
    category: "Company Formation",
  },
  {
    id: "branch-office",
    title: "Branch / Liaison / Project Office",
    shortDesc: "Establish a foreign company's presence in India through branch, liaison or project office.",
    icon: "MapPin",
    category: "Company Formation",
  },

  // ── Tax & GST ──────────────────────────────────────────────────────
  {
    id: "gst-registration",
    title: "GST Registration",
    shortDesc: "Obtain your GSTIN quickly and stay compliant from day one of business operations.",
    icon: "Receipt",
    category: "Tax & GST",
    popular: true,
  },
  {
    id: "gst-filing",
    title: "GST Return Filing",
    shortDesc: "Monthly, quarterly, and annual GST returns filed accurately and on time.",
    icon: "FileText",
    category: "Tax & GST",
  },
  {
    id: "gst-amendment",
    title: "GST Amendment / Cancellation",
    shortDesc: "Amend GST registration details or cancel your GSTIN with full government compliance support.",
    icon: "FilePen",
    category: "Tax & GST",
  },
  {
    id: "income-tax-return",
    title: "Income Tax Return",
    shortDesc: "Expert ITR filing for individuals, firms, and companies across all tax slabs.",
    icon: "IndianRupee",
    category: "Tax & GST",
    popular: true,
  },
  {
    id: "tds-return",
    title: "TDS Return Filing",
    shortDesc: "Accurate and timely TDS return filing (24Q, 26Q, 27Q) with Form 16 / 16A generation.",
    icon: "ClipboardList",
    category: "Tax & GST",
  },
  {
    id: "advance-tax",
    title: "Advance Tax Calculation & Payment",
    shortDesc: "Calculate and pay advance tax in four instalments to avoid interest under Sec 234B/234C.",
    icon: "CalendarClock",
    category: "Tax & GST",
  },
  {
    id: "tax-audit",
    title: "Tax Audit (Sec 44AB)",
    shortDesc: "Mandatory tax audit under Section 44AB by qualified CAs with full report preparation.",
    icon: "Search",
    category: "Tax & GST",
  },
  {
    id: "transfer-pricing",
    title: "Transfer Pricing Study",
    shortDesc: "Benchmarking study and Form 3CEB for international transactions with associated enterprises.",
    icon: "ArrowLeftRight",
    category: "Tax & GST",
  },

  // ── MCA / ROC Compliance ───────────────────────────────────────────
  {
    id: "roc-compliance",
    title: "ROC Annual Filing (Pvt Ltd)",
    shortDesc: "Annual ROC compliance — AOC-4 and MGT-7 filings — for Private Limited Companies.",
    icon: "FolderOpen",
    category: "MCA / ROC Compliance",
    popular: true,
  },
  {
    id: "llp-annual-filing",
    title: "LLP Annual Filing",
    shortDesc: "Annual LLP compliance — Form 11 (Annual Return) and Form 8 (Statement of Accounts).",
    icon: "Folder",
    category: "MCA / ROC Compliance",
  },
  {
    id: "director-kyc",
    title: "Director KYC (DIR-3 KYC)",
    shortDesc: "Annual DIR-3 KYC filing to keep your Director Identification Number active and compliant.",
    icon: "IdCard",
    category: "MCA / ROC Compliance",
  },
  {
    id: "change-in-directors",
    title: "Change in Directors / Shareholders",
    shortDesc: "Add, remove or change directors and shareholders with proper MCA filings and board resolutions.",
    icon: "UserCog",
    category: "MCA / ROC Compliance",
  },
  {
    id: "increase-authorised-capital",
    title: "Increase Authorised Capital",
    shortDesc: "Increase your company's authorised share capital by filing SH-7 and MGT-14 with MCA.",
    icon: "TrendingUp",
    category: "MCA / ROC Compliance",
  },
  {
    id: "registered-office-change",
    title: "Registered Office Change",
    shortDesc: "Change your company's registered office address with INC-22 filing and ROC approval.",
    icon: "MapPinned",
    category: "MCA / ROC Compliance",
  },
  {
    id: "company-name-change",
    title: "Company Name Change",
    shortDesc: "Change your company name through the MCA with INC-1, EGM resolution and fresh COI.",
    icon: "Pencil",
    category: "MCA / ROC Compliance",
  },
  {
    id: "company-closure",
    title: "Strike Off / Company Closure",
    shortDesc: "Voluntarily close your company through Fast Track Exit (STK-2) or NCLT winding-up process.",
    icon: "XCircle",
    category: "MCA / ROC Compliance",
  },

  // ── Startup & MSME ─────────────────────────────────────────────────
  {
    id: "startup-india",
    title: "Startup India (DPIIT)",
    shortDesc: "DPIIT recognition for tax exemptions, funding access, and government schemes.",
    icon: "Rocket",
    category: "Startup & MSME",
  },
  {
    id: "msme-registration",
    title: "MSME / Udyam Registration",
    shortDesc: "Get your Udyam certificate and unlock government benefits for your business.",
    icon: "Award",
    category: "Startup & MSME",
  },
  {
    id: "iec-registration",
    title: "IEC Registration",
    shortDesc: "Import Export Code registration for businesses dealing in international trade.",
    icon: "Plane",
    category: "Startup & MSME",
  },
  {
    id: "fssai-license",
    title: "FSSAI Food License",
    shortDesc: "Obtain FSSAI Basic, State or Central license for your food business — mandatory compliance.",
    icon: "UtensilsCrossed",
    category: "Startup & MSME",
    popular: true,
  },
  {
    id: "professional-tax",
    title: "Professional Tax Registration",
    shortDesc: "Register for Professional Tax (PT) in your state — mandatory for employers and professionals.",
    icon: "Briefcase",
    category: "Startup & MSME",
  },
  {
    id: "trade-license",
    title: "Trade License",
    shortDesc: "Obtain a Municipal Trade License to legally operate your business from a commercial location.",
    icon: "Store",
    category: "Startup & MSME",
  },
  {
    id: "drug-license",
    title: "Drug License",
    shortDesc: "Obtain Retail, Wholesale or Manufacturing Drug License from the State Drug Authority.",
    icon: "Pill",
    category: "Startup & MSME",
  },
  {
    id: "psara-license",
    title: "PSARA License",
    shortDesc: "Private Security Agencies Regulation Act license for security guard agencies in India.",
    icon: "Shield",
    category: "Startup & MSME",
  },
  {
    id: "lmpc-registration",
    title: "LMPC Registration",
    shortDesc: "Legal Metrology Packaged Commodities registration for importers and packers of pre-packaged goods.",
    icon: "Package",
    category: "Startup & MSME",
  },

  // ── Intellectual Property ──────────────────────────────────────────
  {
    id: "trademark-registration",
    title: "Trademark Registration",
    shortDesc: "Protect your brand identity with trademark registration and monitoring services.",
    icon: "ShieldCheck",
    category: "Intellectual Property",
  },
  {
    id: "trademark-objection",
    title: "Trademark Objection Reply",
    shortDesc: "Expert reply to trademark examination report objections to save your trademark application.",
    icon: "MessageSquareWarning",
    category: "Intellectual Property",
  },
  {
    id: "trademark-renewal",
    title: "Trademark Renewal",
    shortDesc: "Renew your trademark registration every 10 years to maintain your exclusive brand rights.",
    icon: "RefreshCw",
    category: "Intellectual Property",
  },
  {
    id: "copyright-registration",
    title: "Copyright Registration",
    shortDesc: "Register copyright for literary, artistic, musical, software or film works under Copyright Act.",
    icon: "Copyright",
    category: "Intellectual Property",
  },
  {
    id: "patent-registration",
    title: "Patent Registration",
    shortDesc: "Protect your invention with a patent — filing, examination and grant through the Indian Patent Office.",
    icon: "Lightbulb",
    category: "Intellectual Property",
  },
  {
    id: "design-registration",
    title: "Design Registration",
    shortDesc: "Register the visual appearance of your product design under the Designs Act, 2000.",
    icon: "Palette",
    category: "Intellectual Property",
  },

  // ── Payroll & HR ───────────────────────────────────────────────────
  {
    id: "pf-registration",
    title: "PF Registration & ECR Filing",
    shortDesc: "EPF employer registration and monthly Electronic Challan-cum-Return (ECR) filing with EPFO.",
    icon: "Landmark",
    category: "Payroll & HR",
  },
  {
    id: "esic-registration",
    title: "ESIC Registration & Returns",
    shortDesc: "ESI employer registration and monthly half-yearly returns for employee insurance compliance.",
    icon: "HeartPulse",
    category: "Payroll & HR",
  },
  {
    id: "payroll-management",
    title: "Payroll Management",
    shortDesc: "End-to-end payroll processing, salary structuring, and statutory compliance.",
    icon: "Wallet",
    category: "Payroll & HR",
  },
  {
    id: "gratuity-trust",
    title: "Gratuity Trust Registration",
    shortDesc: "Set up a private gratuity trust for your company to fulfil Payment of Gratuity Act obligations.",
    icon: "HandHeart",
    category: "Payroll & HR",
  },

  // ── Accounting & Finance ───────────────────────────────────────────
  {
    id: "accounting-bookkeeping",
    title: "Accounting & Bookkeeping",
    shortDesc: "Accurate books, financial statements, and MIS reports for informed decisions.",
    icon: "BookOpen",
    category: "Accounting & Finance",
  },
  {
    id: "virtual-cfo",
    title: "Virtual CFO Services",
    shortDesc: "Senior financial leadership on-demand — budgeting, MIS, fundraising and investor relations.",
    icon: "LineChart",
    category: "Accounting & Finance",
  },
  {
    id: "business-valuation",
    title: "Business Valuation",
    shortDesc: "Certified business valuation report for funding rounds, M&A, ESOPs or regulatory compliance.",
    icon: "BarChart3",
    category: "Accounting & Finance",
  },
  {
    id: "financial-statements",
    title: "Financial Statement Preparation",
    shortDesc: "Prepare P&L, Balance Sheet and Cash Flow Statement as per Companies Act and accounting standards.",
    icon: "FileSpreadsheet",
    category: "Accounting & Finance",
  },
];

export const STATS = [
  { value: 1000, suffix: "+", label: "Businesses Served" },
  { value: 15, suffix: "+", label: "Years Experience" },
  { value: 5000, suffix: "+", label: "Returns Filed" },
  { value: 98, suffix: "%", label: "Client Retention" },
];

export const TESTIMONIALS = [
  {
    name: "Arjun Sharma",
    role: "Founder",
    company: "TechBridge Solutions",
    rating: 5,
    text: "Company Avenue handled our entire Pvt. Ltd. registration and GST setup. Professional, fast, and completely transparent about pricing. Highly recommended for any startup.",
    avatar: "AS",
  },
  {
    name: "Priya Mehta",
    role: "CEO",
    company: "Retail Ventures India",
    rating: 5,
    text: "We've been using their accounting and payroll services for 3 years. Zero errors, always on time. They genuinely feel like a part of our finance team.",
    avatar: "PM",
  },
  {
    name: "Rohan Kapoor",
    role: "Managing Director",
    company: "Kapoor Exports",
    rating: 5,
    text: "Got our IEC registration and trademark done in record time. The team is knowledgeable and available whenever we need them. Great value.",
    avatar: "RK",
  },
  {
    name: "Neha Singh",
    role: "Co-Founder",
    company: "HealthFirst Clinics",
    rating: 5,
    text: "Switched to Company Avenue for our annual ROC filings and ITR. The process is seamless, everything is digital, and their team proactively reminds us about deadlines.",
    avatar: "NS",
  },
  {
    name: "Vikram Patel",
    role: "Director",
    company: "Patel Manufacturing Ltd.",
    rating: 5,
    text: "Excellent MSME and Startup India registration support. Their expertise in compliance gave us confidence to focus on scaling the business.",
    avatar: "VP",
  },
];

export const TRUST_LOGOS = [
  "Google",
  "Startup India",
  "MSME",
  "DPIIT",
  "MCA",
  "GST Network",
  "Income Tax",
  "ISO Certified",
  "Google Reviews",
  "Xero",
  "Zoho Books",
  "QuickBooks",
  "Tally",
  "Slack",
  "Razorpay",
];

export const WHY_CHOOSE = [
  {
    icon: "UserCheck",
    title: "Experienced Professionals",
    desc: "CAs, CSs, and legal experts with 15+ years handling thousands of compliance cases.",
  },
  {
    icon: "Zap",
    title: "Fast Turnaround",
    desc: "Streamlined processes ensure your filings are completed faster than industry standards.",
  },
  {
    icon: "DollarSign",
    title: "Transparent Pricing",
    desc: "No hidden charges. Fixed pricing with detailed breakdowns before you commit.",
  },
  {
    icon: "Headphones",
    title: "Dedicated Relationship Manager",
    desc: "A single point of contact who knows your business and is always reachable.",
  },
  {
    icon: "CheckCircle",
    title: "End-to-End Compliance",
    desc: "From registration to annual filings — we handle it all so you can focus on growth.",
  },
  {
    icon: "Monitor",
    title: "100% Online Process",
    desc: "Fully digital workflow with secure document sharing, e-signatures, and live tracking.",
  },
];

export const PROCESS_STEPS = [
  {
    step: "01",
    title: "Free Consultation",
    desc: "Discuss your requirements with our expert team. We assess your needs and recommend the right services.",
  },
  {
    step: "02",
    title: "Document Collection",
    desc: "We provide a precise document checklist. Upload securely through our digital portal.",
  },
  {
    step: "03",
    title: "Application Filing",
    desc: "Our experts prepare and file accurate applications with the relevant government authorities.",
  },
  {
    step: "04",
    title: "Government Processing",
    desc: "We track your application status and liaise with authorities for any clarifications required.",
  },
  {
    step: "05",
    title: "Approval & Delivery",
    desc: "Certificates and documents are delivered digitally to your email and dashboard.",
  },
  {
    step: "06",
    title: "Ongoing Support",
    desc: "Your dedicated manager ensures continued compliance with proactive reminders and advisory.",
  },
];

export const INDUSTRIES = [
  { name: "IT & Technology", icon: "Monitor", desc: "Software, SaaS, IT services & digital agencies" },
  { name: "Manufacturing", icon: "Factory", desc: "MSME, large-scale, and export manufacturers" },
  { name: "Healthcare", icon: "Heart", desc: "Clinics, diagnostics, pharma & health startups" },
  { name: "Retail & E-commerce", icon: "ShoppingBag", desc: "Online stores, marketplaces & physical retail" },
  { name: "Import & Export", icon: "Globe", desc: "Trading businesses with IEC & customs needs" },
  { name: "Real Estate", icon: "Building", desc: "Developers, agents, and property businesses" },
  { name: "Education", icon: "GraduationCap", desc: "EdTech, schools, coaching & training institutes" },
  { name: "Hospitality", icon: "Hotel", desc: "Hotels, restaurants, food & beverage businesses" },
  { name: "Finance", icon: "TrendingUp", desc: "NBFCs, brokers, fintechs & financial advisors" },
];

export const BLOG_POSTS = [
  {
    id: "private-limited-company-registration-guide",
    title: "Complete Guide to Private Limited Company Registration in India (2024)",
    excerpt: "Everything you need to know about incorporating a Pvt. Ltd. company — documents, timeline, costs, and compliance requirements.",
    category: "Company Registration",
    readTime: "8 min read",
    date: "Dec 12, 2024",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80",
  },
  {
    id: "gst-registration-process",
    title: "GST Registration Process: Step-by-Step Guide for New Businesses",
    excerpt: "A clear walkthrough of the GST registration process, eligibility criteria, required documents, and common mistakes to avoid.",
    category: "GST",
    readTime: "6 min read",
    date: "Dec 8, 2024",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80",
  },
  {
    id: "trademark-registration-india",
    title: "Why Trademark Registration is Critical for Your Brand in India",
    excerpt: "Protect your brand identity before someone else does. Understanding trademark classes, filing timelines, and enforcement.",
    category: "Trademark",
    readTime: "5 min read",
    date: "Nov 28, 2024",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80",
  },
];
