export const COMPANY = {
  name: "Company Avenue Advisory",
  fullName: "Company Avenue Advisory Pvt. Ltd.",
  tagline: "Trusted Business Compliance Partner",
  email: "info@companyavenueadvisory.com",
  phone: "+91 99537 19111",
  whatsapp: "+919953719111",
  address: "209, Jaina Tower 1, District Center, Professor Joginder Singh Marg, Janakpuri, New Delhi, Delhi 110058, India",
  workingHours: "Mon – Sat: 9:00 AM – 7:00 PM",
  website: "https://companyavenueadvisory.com",
  gstin: "07AABCC1234D1Z5",
  cin: "U74999MH2015PTC260940",
  founded: "2009",
};

export const NAV_LINKS = [
  {
    label: "Start Business",
    href: "/services",
    children: [
      {
        group: "Indian Companies",
        items: [
          { label: "Private Limited Company", href: "/services/private-limited-company" },
          { label: "LLP Registration", href: "/services/llp-registration" },
          { label: "One Person Company (OPC)", href: "/services/one-person-company" },
          { label: "Partnership Firm", href: "/services/partnership-firm" },
          { label: "Sole Proprietorship", href: "/services/sole-proprietorship" },
          { label: "Section 8 (NGO) Company", href: "/services/section-8-company" },
          { label: "Nidhi Company", href: "/services/nidhi-company" },
          { label: "Producer Company", href: "/services/producer-company" },
        ],
      },
      {
        group: "Special Entities",
        items: [
          { label: "Public Limited Company", href: "/services/public-limited-company" },
          { label: "NBFC Registration", href: "/services/nbfc-registration" },
          { label: "Chit Fund Company", href: "/services/chit-fund-company" },
          { label: "Microfinance Company (MFI)", href: "/services/microfinance-company" },
        ],
      },
      {
        group: "Foreign Business in India",
        items: [
          { label: "Indian Subsidiary Company", href: "/services/indian-subsidiary" },
          { label: "Branch / Liaison Office", href: "/services/branch-office" },
        ],
      },
      {
        group: "Quick Picks",
        items: [
          { label: "LLP vs Pvt Ltd Comparison", href: "/calculators/llp-vs-pvt-ltd" },
          { label: "Business Structure Advisor", href: "/calculators/business-structure-advisor" },
          { label: "Registration Cost Calculator", href: "/calculators/company-registration-cost" },
        ],
      },
    ],
  },
  {
    label: "IPR",
    href: "/services",
    children: [
      {
        group: "Trademark",
        items: [
          { label: "Trademark Registration", href: "/services/trademark-registration" },
          { label: "Trademark Objection Reply", href: "/services/trademark-objection" },
          { label: "Trademark Renewal", href: "/services/trademark-renewal" },
          { label: "Trademark Watch Service", href: "/services/trademark-watch" },
          { label: "Trademark Assignment", href: "/services/trademark-assignment" },
        ],
      },
      {
        group: "International IP",
        items: [
          { label: "International Trademark (Madrid)", href: "/services/international-trademark" },
          { label: "GI Tag Registration", href: "/services/gi-tag-registration" },
        ],
      },
      {
        group: "Other IP Rights",
        items: [
          { label: "Copyright Registration", href: "/services/copyright-registration" },
          { label: "Patent Registration", href: "/services/patent-registration" },
          { label: "Patent Search & Drafting", href: "/services/patent-search" },
          { label: "Design Registration", href: "/services/design-registration" },
        ],
      },
    ],
  },
  {
    label: "Tax & Payroll",
    href: "/services",
    children: [
      {
        group: "GST Services",
        items: [
          { label: "GST Registration", href: "/services/gst-registration" },
          { label: "GST Return Filing", href: "/services/gst-filing" },
          { label: "GST Amendment / Cancellation", href: "/services/gst-amendment" },
          { label: "GST LUT Filing", href: "/services/gst-lut-filing" },
        ],
      },
      {
        group: "Income Tax",
        items: [
          { label: "Income Tax Return (ITR)", href: "/services/income-tax-return" },
          { label: "TDS Return Filing", href: "/services/tds-return" },
          { label: "Advance Tax Payment", href: "/services/advance-tax" },
          { label: "Tax Audit (Sec 44AB)", href: "/services/tax-audit" },
          { label: "Transfer Pricing Study", href: "/services/transfer-pricing" },
          { label: "12A & 80G Registration", href: "/services/12a-80g-registration" },
        ],
      },
      {
        group: "Labour Law & HR",
        items: [
          { label: "PF Registration & Filing", href: "/services/pf-registration" },
          { label: "ESIC Registration", href: "/services/esic-registration" },
          { label: "Payroll Management", href: "/services/payroll-management" },
          { label: "Shops & Establishment Registration", href: "/services/shops-establishment" },
          { label: "Labour Law Compliance", href: "/services/labour-law-compliance" },
          { label: "POSH Compliance", href: "/services/posh-compliance" },
          { label: "Factories Act Compliance", href: "/services/factories-act" },
          { label: "Gratuity Trust Registration", href: "/services/gratuity-trust" },
        ],
      },
      {
        group: "Accounting & CFO",
        items: [
          { label: "Accounting & Bookkeeping", href: "/services/accounting-bookkeeping" },
          { label: "Virtual CFO Services", href: "/services/virtual-cfo" },
          { label: "Financial Statements", href: "/services/financial-statements" },
          { label: "Business Valuation", href: "/services/business-valuation" },
        ],
      },
    ],
  },
  {
    label: "Compliance",
    href: "/services",
    children: [
      {
        group: "Annual Compliance",
        items: [
          { label: "ROC Annual Filing (Pvt Ltd)", href: "/services/roc-compliance" },
          { label: "LLP Annual Filing", href: "/services/llp-annual-filing" },
          { label: "Director KYC (DIR-3)", href: "/services/director-kyc" },
          { label: "Post-Incorporation Compliance", href: "/services/post-incorporation-compliance" },
          { label: "XBRL Filing", href: "/services/xbrl-filing" },
          { label: "AGM & Board Meeting Services", href: "/services/agm-services" },
        ],
      },
      {
        group: "Company Changes",
        items: [
          { label: "Change in Directors", href: "/services/change-in-directors" },
          { label: "Increase Authorised Capital", href: "/services/increase-authorised-capital" },
          { label: "Registered Office Change", href: "/services/registered-office-change" },
          { label: "Company Name Change", href: "/services/company-name-change" },
          { label: "Share Transfer & Transmission", href: "/services/share-transfer" },
          { label: "Strike Off / Company Closure", href: "/services/company-closure" },
        ],
      },
      {
        group: "Business Conversion",
        items: [
          { label: "Proprietorship to Pvt Ltd", href: "/services/proprietorship-to-pvtltd" },
          { label: "Partnership to LLP", href: "/services/partnership-to-llp" },
          { label: "LLP to Private Limited Company", href: "/services/llp-to-company" },
        ],
      },
    ],
  },
  {
    label: "Regulatory",
    href: "/services",
    children: [
      {
        group: "Startup & MSME",
        items: [
          { label: "Startup India (DPIIT)", href: "/services/startup-india" },
          { label: "MSME / Udyam Registration", href: "/services/msme-registration" },
          { label: "IEC Registration (Import-Export)", href: "/services/iec-registration" },
          { label: "APEDA Registration", href: "/services/apeda-registration" },
        ],
      },
      {
        group: "Licenses & Registrations",
        items: [
          { label: "FSSAI Food License", href: "/services/fssai-license" },
          { label: "Professional Tax Registration", href: "/services/professional-tax" },
          { label: "Trade License", href: "/services/trade-license" },
          { label: "Drug License", href: "/services/drug-license" },
          { label: "PSARA License", href: "/services/psara-license" },
          { label: "LMPC Registration", href: "/services/lmpc-registration" },
          { label: "AYUSH License", href: "/services/ayush-license" },
        ],
      },
      {
        group: "Industrial & Environment",
        items: [
          { label: "ISO Certification", href: "/services/iso-certification" },
          { label: "BIS Registration", href: "/services/bis-registration" },
          { label: "Environment Clearance (PCB)", href: "/services/environment-clearance" },
          { label: "DOT / Telecom License", href: "/services/dot-telecom-license" },
          { label: "Barcode Registration", href: "/services/barcode-registration" },
          { label: "EPR Registration", href: "/services/epr-registration" },
        ],
      },
    ],
  },
  {
    label: "Tools",
    href: "/calculators",
    children: [
      {
        group: "Calculators & Tools",
        items: [
          { label: "GST Calculator", href: "/calculators/gst-calculator" },
          { label: "Income Tax Calculator", href: "/calculators/income-tax-calculator" },
          { label: "TDS Rate Finder", href: "/calculators/tds-rate-finder" },
          { label: "Company Registration Cost", href: "/calculators/company-registration-cost" },
          { label: "LLP vs Pvt Ltd Comparison", href: "/calculators/llp-vs-pvt-ltd" },
          { label: "Business Structure Advisor", href: "/calculators/business-structure-advisor" },
          { label: "Annual Compliance Cost Calculator", href: "/calculators/compliance-cost-calculator" },
        ],
      },
      {
        group: "Verification Tools",
        items: [
          { label: "GST Verification", href: "/verify/gst-verification" },
          { label: "PAN Verification", href: "/verify/pan-verification" },
          { label: "Company & Director Verification", href: "/verify/company-verification" },
          { label: "Trademark Class Finder", href: "/verify/trademark-class-finder" },
          { label: "Company Name Search", href: "/verify/company-name-search" },
        ],
      },
    ],
  },
  { label: "Pricing", href: "/pricing" },
  { label: "Get Help", href: "/contact", variant: "gethelp" as const },
];

export const SERVICES = [
  // ── Company Formation ──────────────────────────────────────────────
  {
    id: "private-limited-company",
    title: "Private Limited Company",
    shortDesc: "Incorporate your Pvt. Ltd. company with end-to-end support and fast government processing.",
    icon: "Building2",
    category: "Company Formation",
    popular: true,
  },
  {
    id: "llp-registration",
    title: "LLP Registration",
    shortDesc: "Register a Limited Liability Partnership with flexible structure and lower compliance burden.",
    icon: "Users",
    category: "Company Formation",
  },
  {
    id: "one-person-company",
    title: "One Person Company",
    shortDesc: "Start your solo business journey with complete limited liability protection.",
    icon: "User",
    category: "Company Formation",
  },
  {
    id: "partnership-firm",
    title: "Partnership Firm Registration",
    shortDesc: "Register a traditional partnership firm with a deed — ideal for small businesses run by 2–20 partners.",
    icon: "Handshake",
    category: "Company Formation",
  },
  {
    id: "sole-proprietorship",
    title: "Sole Proprietorship",
    shortDesc: "Set up a sole proprietorship with GST, bank account and business identity — simplest business form.",
    icon: "PersonStanding",
    category: "Company Formation",
  },
  {
    id: "section-8-company",
    title: "Section 8 Company (NGO)",
    shortDesc: "Register a non-profit company for charitable, educational, or social objectives under Section 8.",
    icon: "Heart",
    category: "Company Formation",
  },
  {
    id: "nidhi-company",
    title: "Nidhi Company Registration",
    shortDesc: "Register a Nidhi Company to promote savings and lending among members — RBI-governed.",
    icon: "PiggyBank",
    category: "Company Formation",
  },
  {
    id: "producer-company",
    title: "Producer Company Registration",
    shortDesc: "Incorporate a Producer Company for farmers, artisans and primary producers with cooperative benefits.",
    icon: "Sprout",
    category: "Company Formation",
  },
  {
    id: "indian-subsidiary",
    title: "Indian Subsidiary of Foreign Company",
    shortDesc: "Set up a 100% foreign-owned Indian subsidiary under FEMA and Companies Act regulations.",
    icon: "Globe",
    category: "Company Formation",
  },
  {
    id: "branch-office",
    title: "Branch / Liaison / Project Office",
    shortDesc: "Establish a foreign company's presence in India through branch, liaison or project office.",
    icon: "MapPin",
    category: "Company Formation",
  },
  {
    id: "public-limited-company",
    title: "Public Limited Company",
    shortDesc: "Incorporate a Public Limited Company — ideal for large businesses seeking public funding and stock market listing.",
    icon: "Building2",
    category: "Company Formation",
  },
  {
    id: "nbfc-registration",
    title: "NBFC Registration",
    shortDesc: "Register a Non-Banking Financial Company with RBI — for lending, investment, and financial services.",
    icon: "Landmark",
    category: "Company Formation",
  },
  {
    id: "chit-fund-company",
    title: "Chit Fund Company Registration",
    shortDesc: "Register a Chit Fund Company under the Chit Funds Act, 1982 with state government approval.",
    icon: "PiggyBank",
    category: "Company Formation",
  },
  {
    id: "microfinance-company",
    title: "Microfinance Company (MFI)",
    shortDesc: "Register a Microfinance Institution as Section 8 Company or NBFC-MFI for lending to low-income borrowers.",
    icon: "HandCoins",
    category: "Company Formation",
  },

  // ── Tax & GST ──────────────────────────────────────────────────────
  {
    id: "gst-registration",
    title: "GST Registration",
    shortDesc: "Obtain your GSTIN quickly and stay compliant from day one of business operations.",
    icon: "Receipt",
    category: "Tax & GST",
    popular: true,
  },
  {
    id: "gst-filing",
    title: "GST Return Filing",
    shortDesc: "Monthly, quarterly, and annual GST returns filed accurately and on time.",
    icon: "FileText",
    category: "Tax & GST",
  },
  {
    id: "gst-amendment",
    title: "GST Amendment / Cancellation",
    shortDesc: "Amend GST registration details or cancel your GSTIN with full government compliance support.",
    icon: "FilePen",
    category: "Tax & GST",
  },
  {
    id: "income-tax-return",
    title: "Income Tax Return",
    shortDesc: "Expert ITR filing for individuals, firms, and companies across all tax slabs.",
    icon: "IndianRupee",
    category: "Tax & GST",
    popular: true,
  },
  {
    id: "tds-return",
    title: "TDS Return Filing",
    shortDesc: "Accurate and timely TDS return filing (24Q, 26Q, 27Q) with Form 16 / 16A generation.",
    icon: "ClipboardList",
    category: "Tax & GST",
  },
  {
    id: "advance-tax",
    title: "Advance Tax Calculation & Payment",
    shortDesc: "Calculate and pay advance tax in four instalments to avoid interest under Sec 234B/234C.",
    icon: "CalendarClock",
    category: "Tax & GST",
  },
  {
    id: "tax-audit",
    title: "Tax Audit (Sec 44AB)",
    shortDesc: "Mandatory tax audit under Section 44AB by qualified CAs with full report preparation.",
    icon: "Search",
    category: "Tax & GST",
  },
  {
    id: "transfer-pricing",
    title: "Transfer Pricing Study",
    shortDesc: "Benchmarking study and Form 3CEB for international transactions with associated enterprises.",
    icon: "ArrowLeftRight",
    category: "Tax & GST",
  },
  {
    id: "gst-lut-filing",
    title: "GST LUT Filing",
    shortDesc: "File Letter of Undertaking (LUT) to export goods and services without payment of IGST.",
    icon: "FileCheck",
    category: "Tax & GST",
  },
  {
    id: "12a-80g-registration",
    title: "12A & 80G Registration",
    shortDesc: "Register your NGO or trust under Section 12A and 80G for income tax exemption and donor tax benefits.",
    icon: "HeartHandshake",
    category: "Tax & GST",
  },
  {
    id: "shops-establishment",
    title: "Shops & Establishment Registration",
    shortDesc: "Mandatory state registration for shops, offices, restaurants, and commercial establishments.",
    icon: "Store",
    category: "Tax & GST",
  },
  {
    id: "labour-law-compliance",
    title: "Labour Law Compliance",
    shortDesc: "End-to-end compliance with Indian labour laws — Minimum Wages, Contract Labour, Bonus Act and more.",
    icon: "ShieldCheck",
    category: "Tax & GST",
  },
  {
    id: "posh-compliance",
    title: "POSH Compliance",
    shortDesc: "Prevention of Sexual Harassment (POSH) Act compliance — ICC setup, policy drafting, and annual report.",
    icon: "Users",
    category: "Tax & GST",
  },
  {
    id: "factories-act",
    title: "Factories Act Compliance",
    shortDesc: "Factory license, annual returns, and ongoing compliance under the Factories Act, 1948.",
    icon: "Factory",
    category: "Tax & GST",
  },

  // ── MCA / ROC Compliance ───────────────────────────────────────────
  {
    id: "roc-compliance",
    title: "ROC Annual Filing (Pvt Ltd)",
    shortDesc: "Annual ROC compliance — AOC-4 and MGT-7 filings — for Private Limited Companies.",
    icon: "FolderOpen",
    category: "MCA / ROC Compliance",
    popular: true,
  },
  {
    id: "llp-annual-filing",
    title: "LLP Annual Filing",
    shortDesc: "Annual LLP compliance — Form 11 (Annual Return) and Form 8 (Statement of Accounts).",
    icon: "Folder",
    category: "MCA / ROC Compliance",
  },
  {
    id: "director-kyc",
    title: "Director KYC (DIR-3 KYC)",
    shortDesc: "Annual DIR-3 KYC filing to keep your Director Identification Number active and compliant.",
    icon: "IdCard",
    category: "MCA / ROC Compliance",
  },
  {
    id: "change-in-directors",
    title: "Change in Directors / Shareholders",
    shortDesc: "Add, remove or change directors and shareholders with proper MCA filings and board resolutions.",
    icon: "UserCog",
    category: "MCA / ROC Compliance",
  },
  {
    id: "increase-authorised-capital",
    title: "Increase Authorised Capital",
    shortDesc: "Increase your company's authorised share capital by filing SH-7 and MGT-14 with MCA.",
    icon: "TrendingUp",
    category: "MCA / ROC Compliance",
  },
  {
    id: "registered-office-change",
    title: "Registered Office Change",
    shortDesc: "Change your company's registered office address with INC-22 filing and ROC approval.",
    icon: "MapPinned",
    category: "MCA / ROC Compliance",
  },
  {
    id: "company-name-change",
    title: "Company Name Change",
    shortDesc: "Change your company name through the MCA with INC-1, EGM resolution and fresh COI.",
    icon: "Pencil",
    category: "MCA / ROC Compliance",
  },
  {
    id: "company-closure",
    title: "Strike Off / Company Closure",
    shortDesc: "Voluntarily close your company through Fast Track Exit (STK-2) or NCLT winding-up process.",
    icon: "XCircle",
    category: "MCA / ROC Compliance",
  },
  {
    id: "post-incorporation-compliance",
    title: "Post-Incorporation Compliance",
    shortDesc: "Complete all mandatory post-incorporation filings — INC-20A, first board meeting, share allotment, and more.",
    icon: "ClipboardCheck",
    category: "MCA / ROC Compliance",
  },
  {
    id: "xbrl-filing",
    title: "XBRL Filing",
    shortDesc: "XBRL tagging and filing of financial statements for companies mandated by MCA/SEBI regulations.",
    icon: "FileCode",
    category: "MCA / ROC Compliance",
  },
  {
    id: "agm-services",
    title: "AGM & Board Meeting Services",
    shortDesc: "End-to-end AGM and board meeting management — notices, agenda, minutes, and statutory compliance.",
    icon: "CalendarCheck",
    category: "MCA / ROC Compliance",
  },
  {
    id: "share-transfer",
    title: "Share Transfer & Transmission",
    shortDesc: "Legal transfer of shares with SH-4, stamp duty, board resolution, and updated register of members.",
    icon: "ArrowLeftRight",
    category: "MCA / ROC Compliance",
  },
  {
    id: "proprietorship-to-pvtltd",
    title: "Proprietorship to Pvt Ltd Conversion",
    shortDesc: "Convert your sole proprietorship to a Private Limited Company with full business migration support.",
    icon: "TrendingUp",
    category: "MCA / ROC Compliance",
  },
  {
    id: "partnership-to-llp",
    title: "Partnership to LLP Conversion",
    shortDesc: "Convert an existing partnership firm to an LLP — preserving continuity while gaining limited liability.",
    icon: "GitMerge",
    category: "MCA / ROC Compliance",
  },
  {
    id: "llp-to-company",
    title: "LLP to Private Limited Company",
    shortDesc: "Convert your LLP to a Private Limited Company to access equity funding and better corporate governance.",
    icon: "Building2",
    category: "MCA / ROC Compliance",
  },

  // ── Startup & MSME ─────────────────────────────────────────────────
  {
    id: "startup-india",
    title: "Startup India (DPIIT)",
    shortDesc: "DPIIT recognition for tax exemptions, funding access, and government schemes.",
    icon: "Rocket",
    category: "Startup & MSME",
  },
  {
    id: "msme-registration",
    title: "MSME / Udyam Registration",
    shortDesc: "Get your Udyam certificate and unlock government benefits for your business.",
    icon: "Award",
    category: "Startup & MSME",
  },
  {
    id: "iec-registration",
    title: "IEC Registration",
    shortDesc: "Import Export Code registration for businesses dealing in international trade.",
    icon: "Plane",
    category: "Startup & MSME",
  },
  {
    id: "fssai-license",
    title: "FSSAI Food License",
    shortDesc: "Obtain FSSAI Basic, State or Central license for your food business — mandatory compliance.",
    icon: "UtensilsCrossed",
    category: "Startup & MSME",
    popular: true,
  },
  {
    id: "professional-tax",
    title: "Professional Tax Registration",
    shortDesc: "Register for Professional Tax (PT) in your state — mandatory for employers and professionals.",
    icon: "Briefcase",
    category: "Startup & MSME",
  },
  {
    id: "trade-license",
    title: "Trade License",
    shortDesc: "Obtain a Municipal Trade License to legally operate your business from a commercial location.",
    icon: "Store",
    category: "Startup & MSME",
  },
  {
    id: "drug-license",
    title: "Drug License",
    shortDesc: "Obtain Retail, Wholesale or Manufacturing Drug License from the State Drug Authority.",
    icon: "Pill",
    category: "Startup & MSME",
  },
  {
    id: "psara-license",
    title: "PSARA License",
    shortDesc: "Private Security Agencies Regulation Act license for security guard agencies in India.",
    icon: "Shield",
    category: "Startup & MSME",
  },
  {
    id: "lmpc-registration",
    title: "LMPC Registration",
    shortDesc: "Legal Metrology Packaged Commodities registration for importers and packers of pre-packaged goods.",
    icon: "Package",
    category: "Startup & MSME",
  },
  {
    id: "ayush-license",
    title: "AYUSH License",
    shortDesc: "Manufacturing and retail license for Ayurveda, Unani, Siddha, and Homeopathy products.",
    icon: "Leaf",
    category: "Startup & MSME",
  },
  {
    id: "iso-certification",
    title: "ISO Certification",
    shortDesc: "ISO 9001, 14001, 22000, 27001 and other management system certifications for your business.",
    icon: "BadgeCheck",
    category: "Startup & MSME",
  },
  {
    id: "bis-registration",
    title: "BIS Registration (ISI Mark)",
    shortDesc: "Bureau of Indian Standards registration — mandatory ISI Mark for electronics, toys, and regulated products.",
    icon: "ShieldCheck",
    category: "Startup & MSME",
  },
  {
    id: "environment-clearance",
    title: "Environment Clearance (PCB)",
    shortDesc: "Environmental clearance, Consent to Establish (CTE) and Consent to Operate (CTO) from Pollution Control Board.",
    icon: "TreePine",
    category: "Startup & MSME",
  },
  {
    id: "dot-telecom-license",
    title: "DOT / Telecom License",
    shortDesc: "Department of Telecom licenses — ISP, OSP, VNO, and other telecom authorizations from DOT.",
    icon: "Radio",
    category: "Startup & MSME",
  },
  {
    id: "apeda-registration",
    title: "APEDA Registration",
    shortDesc: "APEDA registration for exporters of agricultural and processed food products from India.",
    icon: "Wheat",
    category: "Startup & MSME",
  },
  {
    id: "barcode-registration",
    title: "Barcode Registration (GS1 India)",
    shortDesc: "GS1 India barcode registration for product tracking, retail distribution, and e-commerce compliance.",
    icon: "Barcode",
    category: "Startup & MSME",
  },
  {
    id: "epr-registration",
    title: "EPR Registration",
    shortDesc: "Extended Producer Responsibility registration for plastic, e-waste, and battery manufacturers/importers.",
    icon: "Recycle",
    category: "Startup & MSME",
  },

  // ── Intellectual Property ──────────────────────────────────────────
  {
    id: "trademark-registration",
    title: "Trademark Registration",
    shortDesc: "Protect your brand identity with trademark registration and monitoring services.",
    icon: "ShieldCheck",
    category: "Intellectual Property",
  },
  {
    id: "trademark-objection",
    title: "Trademark Objection Reply",
    shortDesc: "Expert reply to trademark examination report objections to save your trademark application.",
    icon: "MessageSquareWarning",
    category: "Intellectual Property",
  },
  {
    id: "trademark-renewal",
    title: "Trademark Renewal",
    shortDesc: "Renew your trademark registration every 10 years to maintain your exclusive brand rights.",
    icon: "RefreshCw",
    category: "Intellectual Property",
  },
  {
    id: "copyright-registration",
    title: "Copyright Registration",
    shortDesc: "Register copyright for literary, artistic, musical, software or film works under Copyright Act.",
    icon: "Copyright",
    category: "Intellectual Property",
  },
  {
    id: "patent-registration",
    title: "Patent Registration",
    shortDesc: "Protect your invention with a patent — filing, examination and grant through the Indian Patent Office.",
    icon: "Lightbulb",
    category: "Intellectual Property",
  },
  {
    id: "design-registration",
    title: "Design Registration",
    shortDesc: "Register the visual appearance of your product design under the Designs Act, 2000.",
    icon: "Palette",
    category: "Intellectual Property",
  },
  {
    id: "trademark-watch",
    title: "Trademark Watch Service",
    shortDesc: "Monitor trademark registry for conflicting new filings and protect your registered brand automatically.",
    icon: "Eye",
    category: "Intellectual Property",
  },
  {
    id: "trademark-assignment",
    title: "Trademark Assignment & Transfer",
    shortDesc: "Transfer ownership of a registered trademark with TM-P filing and assignment deed.",
    icon: "ArrowRightLeft",
    category: "Intellectual Property",
  },
  {
    id: "international-trademark",
    title: "International Trademark (Madrid)",
    shortDesc: "File international trademark applications via Madrid Protocol to protect your brand in 130+ countries.",
    icon: "Globe",
    category: "Intellectual Property",
  },
  {
    id: "gi-tag-registration",
    title: "GI Tag Registration",
    shortDesc: "Register a Geographical Indication tag for products with special geographical origin and reputation.",
    icon: "MapPin",
    category: "Intellectual Property",
  },
  {
    id: "patent-search",
    title: "Patent Search & Drafting",
    shortDesc: "Prior art search, patentability opinion, and complete patent specification drafting by technical experts.",
    icon: "Search",
    category: "Intellectual Property",
  },

  // ── Payroll & HR ───────────────────────────────────────────────────
  {
    id: "pf-registration",
    title: "PF Registration & ECR Filing",
    shortDesc: "EPF employer registration and monthly Electronic Challan-cum-Return (ECR) filing with EPFO.",
    icon: "Landmark",
    category: "Payroll & HR",
  },
  {
    id: "esic-registration",
    title: "ESIC Registration & Returns",
    shortDesc: "ESI employer registration and monthly half-yearly returns for employee insurance compliance.",
    icon: "HeartPulse",
    category: "Payroll & HR",
  },
  {
    id: "payroll-management",
    title: "Payroll Management",
    shortDesc: "End-to-end payroll processing, salary structuring, and statutory compliance.",
    icon: "Wallet",
    category: "Payroll & HR",
  },
  {
    id: "gratuity-trust",
    title: "Gratuity Trust Registration",
    shortDesc: "Set up a private gratuity trust for your company to fulfil Payment of Gratuity Act obligations.",
    icon: "HandHeart",
    category: "Payroll & HR",
  },

  // ── Accounting & Finance ───────────────────────────────────────────
  {
    id: "accounting-bookkeeping",
    title: "Accounting & Bookkeeping",
    shortDesc: "Accurate books, financial statements, and MIS reports for informed decisions.",
    icon: "BookOpen",
    category: "Accounting & Finance",
  },
  {
    id: "virtual-cfo",
    title: "Virtual CFO Services",
    shortDesc: "Senior financial leadership on-demand — budgeting, MIS, fundraising and investor relations.",
    icon: "LineChart",
    category: "Accounting & Finance",
  },
  {
    id: "business-valuation",
    title: "Business Valuation",
    shortDesc: "Certified business valuation report for funding rounds, M&A, ESOPs or regulatory compliance.",
    icon: "BarChart3",
    category: "Accounting & Finance",
  },
  {
    id: "financial-statements",
    title: "Financial Statement Preparation",
    shortDesc: "Prepare P&L, Balance Sheet and Cash Flow Statement as per Companies Act and accounting standards.",
    icon: "FileSpreadsheet",
    category: "Accounting & Finance",
  },
];

export const STATS = [
  { value: 1000, suffix: "+", label: "Businesses Served" },
  { value: 15, suffix: "+", label: "Years Experience" },
  { value: 5000, suffix: "+", label: "Returns Filed" },
  { value: 98, suffix: "%", label: "Client Retention" },
];

export const TESTIMONIALS = [
  {
    name: "Arjun Sharma",
    role: "Founder",
    company: "TechBridge Solutions",
    rating: 5,
    text: "Company Avenue handled our entire Pvt. Ltd. registration and GST setup. Professional, fast, and completely transparent about pricing. Highly recommended for any startup.",
    avatar: "AS",
  },
  {
    name: "Priya Mehta",
    role: "CEO",
    company: "Retail Ventures India",
    rating: 5,
    text: "We've been using their accounting and payroll services for 3 years. Zero errors, always on time. They genuinely feel like a part of our finance team.",
    avatar: "PM",
  },
  {
    name: "Rohan Kapoor",
    role: "Managing Director",
    company: "Kapoor Exports",
    rating: 5,
    text: "Got our IEC registration and trademark done in record time. The team is knowledgeable and available whenever we need them. Great value.",
    avatar: "RK",
  },
  {
    name: "Neha Singh",
    role: "Co-Founder",
    company: "HealthFirst Clinics",
    rating: 5,
    text: "Switched to Company Avenue for our annual ROC filings and ITR. The process is seamless, everything is digital, and their team proactively reminds us about deadlines.",
    avatar: "NS",
  },
  {
    name: "Vikram Patel",
    role: "Director",
    company: "Patel Manufacturing Ltd.",
    rating: 5,
    text: "Excellent MSME and Startup India registration support. Their expertise in compliance gave us confidence to focus on scaling the business.",
    avatar: "VP",
  },
];

export const TRUST_LOGOS = [
  "Google",
  "Startup India",
  "MSME",
  "DPIIT",
  "MCA",
  "GST Network",
  "Income Tax",
  "ISO Certified",
  "Google Reviews",
  "Xero",
  "Zoho Books",
  "QuickBooks",
  "Tally",
  "Slack",
  "Razorpay",
];

export const WHY_CHOOSE = [
  {
    icon: "UserCheck",
    title: "Experienced Professionals",
    desc: "CAs, CSs, and legal experts with 15+ years handling thousands of compliance cases.",
  },
  {
    icon: "Zap",
    title: "Fast Turnaround",
    desc: "Streamlined processes ensure your filings are completed faster than industry standards.",
  },
  {
    icon: "DollarSign",
    title: "Transparent Pricing",
    desc: "No hidden charges. Fixed pricing with detailed breakdowns before you commit.",
  },
  {
    icon: "Headphones",
    title: "Dedicated Relationship Manager",
    desc: "A single point of contact who knows your business and is always reachable.",
  },
  {
    icon: "CheckCircle",
    title: "End-to-End Compliance",
    desc: "From registration to annual filings — we handle it all so you can focus on growth.",
  },
  {
    icon: "Monitor",
    title: "100% Online Process",
    desc: "Fully digital workflow with secure document sharing, e-signatures, and live tracking.",
  },
];

export const PROCESS_STEPS = [
  {
    step: "01",
    title: "Free Consultation",
    desc: "Discuss your requirements with our expert team. We assess your needs and recommend the right services.",
  },
  {
    step: "02",
    title: "Document Collection",
    desc: "We provide a precise document checklist. Upload securely through our digital portal.",
  },
  {
    step: "03",
    title: "Application Filing",
    desc: "Our experts prepare and file accurate applications with the relevant government authorities.",
  },
  {
    step: "04",
    title: "Government Processing",
    desc: "We track your application status and liaise with authorities for any clarifications required.",
  },
  {
    step: "05",
    title: "Approval & Delivery",
    desc: "Certificates and documents are delivered digitally to your email and dashboard.",
  },
  {
    step: "06",
    title: "Ongoing Support",
    desc: "Your dedicated manager ensures continued compliance with proactive reminders and advisory.",
  },
];

export const INDUSTRIES = [
  { name: "IT & Technology", icon: "Monitor", desc: "Software, SaaS, IT services & digital agencies" },
  { name: "Manufacturing", icon: "Factory", desc: "MSME, large-scale, and export manufacturers" },
  { name: "Healthcare", icon: "Heart", desc: "Clinics, diagnostics, pharma & health startups" },
  { name: "Retail & E-commerce", icon: "ShoppingBag", desc: "Online stores, marketplaces & physical retail" },
  { name: "Import & Export", icon: "Globe", desc: "Trading businesses with IEC & customs needs" },
  { name: "Real Estate", icon: "Building", desc: "Developers, agents, and property businesses" },
  { name: "Education", icon: "GraduationCap", desc: "EdTech, schools, coaching & training institutes" },
  { name: "Hospitality", icon: "Hotel", desc: "Hotels, restaurants, food & beverage businesses" },
  { name: "Finance", icon: "TrendingUp", desc: "NBFCs, brokers, fintechs & financial advisors" },
];

export const BLOG_POSTS = [
  {
    id: "private-limited-company-registration-guide",
    title: "Complete Guide to Private Limited Company Registration in India (2024)",
    excerpt: "Everything you need to know about incorporating a Pvt. Ltd. company — documents, timeline, costs, and compliance requirements.",
    category: "Company Registration",
    readTime: "8 min read",
    date: "Dec 12, 2024",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80",
  },
  {
    id: "gst-registration-process",
    title: "GST Registration Process: Step-by-Step Guide for New Businesses",
    excerpt: "A clear walkthrough of the GST registration process, eligibility criteria, required documents, and common mistakes to avoid.",
    category: "GST",
    readTime: "6 min read",
    date: "Dec 8, 2024",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80",
  },
  {
    id: "trademark-registration-india",
    title: "Why Trademark Registration is Critical for Your Brand in India",
    excerpt: "Protect your brand identity before someone else does. Understanding trademark classes, filing timelines, and enforcement.",
    category: "Trademark",
    readTime: "5 min read",
    date: "Nov 28, 2024",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80",
  },
];
