// FAQ content for GSTFilingPage.
// Kept in a plain (non-"use client") module so both the client component that
// renders it and the server page that emits FAQPage JSON-LD can import it —
// values can't cross the client/server boundary out of a "use client" file.

export const faqs = [
  { q: "What is a GST Return?", a: "A GST Return is a document every GST-registered taxpayer must file with the tax authorities. It contains details of sales, purchases, tax collected on sales (output tax), and tax paid on purchases (input tax credit). Returns are filed monthly, quarterly, or annually depending on the taxpayer category." },
  { q: "Who needs to file GST returns?", a: "Every GST-registered business must file returns, including regular taxpayers, composition dealers, e-commerce operators, non-resident taxable persons, and input service distributors. Even if there is no business activity, a Nil Return must be filed." },
  { q: "What is GSTR-1?", a: "GSTR-1 is a monthly or quarterly return containing details of all outward taxable supplies (sales). It includes B2B invoices, B2C invoices, credit/debit notes, and export details. Regular taxpayers with turnover above ₹5 crore file monthly; others may opt for quarterly filing under QRMP." },
  { q: "What is GSTR-3B?", a: "GSTR-3B is a monthly or quarterly self-declared summary return where taxpayers declare their total tax liability, input tax credit claimed, and net tax payable. It must be filed along with the tax payment by the 20th of the following month (regular taxpayers)." },
  { q: "What is GSTR-9?", a: "GSTR-9 is the annual GST return filed by regular taxpayers consolidating all monthly/quarterly returns filed during the financial year. It must be filed by December 31st following the end of the financial year. It is mandatory for taxpayers with turnover above ₹2 crore." },
  { q: "Can I file a Nil Return?", a: "Yes. If there are no sales or purchases during a period, you must file a Nil Return (GSTR-1 and GSTR-3B with zero values). Failing to file even a Nil Return attracts late fees of ₹20/day (₹10 CGST + ₹10 SGST)." },
  { q: "What happens if I miss the due date?", a: "Late filing attracts a fee of ₹50/day (₹25 CGST + ₹25 SGST) for regular returns, subject to a maximum cap. For Nil returns, the fee is ₹20/day. Additionally, interest @ 18% per annum applies on any unpaid tax from the due date." },
  { q: "How much is the GST late fee?", a: "₹50/day for regular returns (₹25 CGST + ₹25 SGST). ₹20/day for Nil returns (₹10 CGST + ₹10 SGST). The government periodically introduces amnesty schemes to waive late fees for older returns — we help you take advantage of such schemes." },
  { q: "Can I revise GST returns?", a: "GSTR-3B cannot be revised once filed. However, corrections to GSTR-1 can be made in subsequent periods through amendments. For significant errors, rectification through amended returns in the next filing period is the standard approach." },
  { q: "How is Input Tax Credit (ITC) claimed?", a: "ITC is claimed in GSTR-3B based on invoices reflected in your GSTR-2B (auto-populated from supplier filings). You can only claim ITC for invoices where the supplier has filed their GSTR-1 and the amount appears in your GSTR-2B." },
  { q: "What is invoice matching?", a: "Invoice matching is the process of reconciling your purchase records with GSTR-2B data. It ensures that the ITC you claim matches what suppliers have reported. Mismatches can lead to ITC rejection and demand notices from the GST department." },
  { q: "Do I need to file returns if there are no sales?", a: "Yes. Even if there are zero sales in a period, a Nil Return must be filed. Failure to file attracts late fees regardless of whether you had any business activity or not." },
  { q: "Can I file returns myself?", a: "Yes, you can file on the GST portal (gst.gov.in). However, professional filing ensures accurate data entry, ITC reconciliation, HSN/SAC validation, and timely submission — minimising the risk of errors, notices, and penalties." },
  { q: "What documents are required for filing?", a: "Sales register, purchase register, all invoices (sales and purchase), bank statements, e-way bills, expense records, and previous filed return data. We provide a complete checklist upon engagement." },
  { q: "Can Company Avenue file monthly returns on my behalf?", a: "Yes. We offer monthly, quarterly, and annual GST return filing packages. Your dedicated compliance manager collects data, reconciles ITC, prepares the return, gets your approval, and files — all on time." },
  { q: "What is the annual GST return (GSTR-9)?", a: "GSTR-9 is an annual return consolidating all GSTR-1 and GSTR-3B data for the financial year. It reconciles reported figures, highlights discrepancies, and is due by December 31st. It is mandatory for taxpayers with annual turnover above ₹2 crore." },
  { q: "Is GST audit mandatory?", a: "GSTR-9C (self-certified reconciliation statement) is required for taxpayers with annual turnover above ₹5 crore. It reconciles books of accounts with the annual return and does not require a CA certificate (since 2021) but must be accurate." },
  { q: "How long should GST records be maintained?", a: "GST records including invoices, returns, tax payment challans, and books of accounts must be maintained for a minimum of 6 years from the due date of the annual return for the relevant year." },
  { q: "How much does GST return filing cost?", a: "Our monthly GST return filing packages start from ₹499/month. Pricing depends on the number of invoices, return type, and frequency. We offer transparent fixed pricing with no hidden charges. Request a free quote today." },
  { q: "How can I avoid GST penalties?", a: "File returns on or before due dates, ensure ITC reconciliation monthly, use correct HSN/SAC codes, verify GSTINs of counterparties, and engage a professional compliance partner. Our managed compliance service ensures zero late filings." },
];
