// FAQ content for ITRPage.
// Kept in a plain (non-"use client") module so both the client component that
// renders it and the server page that emits FAQPage JSON-LD can import it —
// values can't cross the client/server boundary out of a "use client" file.

export const faqs = [
  { q: "What is an Income Tax Return (ITR)?", a: "An Income Tax Return (ITR) is a form filed with the Income Tax Department reporting your annual income, taxes paid, deductions claimed, and net tax liability or refund due. It is filed annually and is mandatory for individuals and entities above the prescribed threshold." },
  { q: "Who should file an ITR?", a: "Individuals with income above the basic exemption limit (₹2.5 lakh for below 60, ₹3 lakh for 60–80, ₹5 lakh for above 80), all companies and LLPs regardless of income, individuals with foreign assets, those seeking refunds, and anyone with capital gains or multiple income sources." },
  { q: "Which ITR form should I choose?", a: "ITR-1 for salaried with simple income; ITR-2 for capital gains; ITR-3 for business/professional income; ITR-4 for presumptive income; ITR-5 for LLPs and firms; ITR-6 for companies; ITR-7 for trusts and NGOs. We assess your income profile and select the correct form." },
  { q: "Can I file ITR without Form 16?", a: "Yes. Form 16 is not mandatory. You can file using salary slips, Form 26AS, the Annual Information Statement (AIS), and bank statements. We reconcile all available data to prepare an accurate return even without Form 16." },
  { q: "How can I claim a tax refund?", a: "File your ITR accurately reporting all TDS deducted and advance tax paid. If the total tax paid exceeds your actual tax liability, the excess is refunded directly to your pre-validated bank account linked with PAN. Refunds are typically processed within 20–45 days of e-verification." },
  { q: "What happens if I miss the due date?", a: "Late filing attracts ₹5,000 late fee (₹1,000 if income is below ₹5 lakh). Interest @ 1% per month applies on unpaid tax. Capital and business losses cannot be carried forward. The return can still be filed as a Belated Return by 31st December of the assessment year." },
  { q: "Can freelancers file ITR?", a: "Yes. Freelancers with professional income file ITR-3 or ITR-4 (under presumptive scheme 44ADA if eligible). They can claim business expenses, home office costs, and other professional deductions to reduce taxable income." },
  { q: "Is Aadhaar mandatory for ITR filing?", a: "Yes. Aadhaar is mandatory for ITR filing under Section 139AA. Your PAN must be linked with Aadhaar before filing. E-verification of the filed return can also be done via Aadhaar OTP." },
  { q: "How long does refund processing take?", a: "Typically 20–45 days after e-verification for straightforward returns. Complex returns with capital gains, foreign income, or audit requirements may take longer. Refunds are credited directly to the pre-validated bank account." },
  { q: "Can I revise my ITR?", a: "Yes. A revised return can be filed under Section 139(5) to correct any omission or error in the original return. Revised returns can be filed up to 31st December of the assessment year or before assessment, whichever is earlier." },
  { q: "What is e-verification and is it mandatory?", a: "E-verification confirms your identity after filing and completes the submission process. It can be done via Aadhaar OTP, net banking, demat account EVC, or Digital Signature Certificate. It must be completed within 30 days of filing — else the return is treated as not filed." },
  { q: "Do I need to file ITR if TDS is already deducted?", a: "Yes. TDS deduction does not exempt you from filing. Filing is required to reconcile TDS, claim excess TDS as refund, disclose all income sources, and maintain compliance — especially if you have multiple income streams." },
  { q: "Can businesses file ITR online?", a: "Yes. All businesses including proprietorships, partnerships, LLPs, and companies file ITR through the Income Tax Portal. Audit-required businesses must upload the audit report before filing. We handle the complete process." },
  { q: "Can LLPs file ITR through Company Avenue?", a: "Yes. LLPs file ITR-5 and must have their books audited if turnover exceeds prescribed limits. We handle LLP audit, ITR preparation, and filing with full compliance." },
  { q: "Can companies file ITR through Company Avenue?", a: "Yes. Companies file ITR-6 and must attach the Board's Report, Financial Statements, and Tax Audit Report. Our team of CAs handles company ITR filing end-to-end." },
  { q: "How much does ITR filing cost?", a: "Individual ITR-1 starts from ₹499. Complex returns with capital gains, business income, or foreign assets are priced based on complexity. We provide transparent, fixed pricing upfront with no hidden charges." },
  { q: "Can I claim deductions under 80C?", a: "Yes. Section 80C allows deductions up to ₹1.5 lakh for PPF, ELSS, LIC premium, NSC, ELSS funds, home loan principal, EPF, and children's tuition fees. We identify and claim all eligible 80C investments from your documents." },
  { q: "Can I file a NIL return?", a: "Yes. A NIL return is filed when your income is below the taxable threshold. While not mandatory in most cases, filing a NIL return maintains your compliance record, is useful for loan applications, and establishes your tax filing history." },
  { q: "How many years should I keep tax records?", a: "Income tax records must be kept for 6 years from the end of the relevant assessment year as per Section 149. For cases involving serious fraud or foreign assets, records should be maintained for up to 16 years." },
  { q: "Can I switch between Old and New Tax Regime?", a: "Salaried individuals and those without business income can switch between old and new regime every year. Individuals with business income can switch only once from new to old regime. We analyse both regimes for you and recommend the most tax-efficient option." },
];
