// FAQ content for MSMERegistrationPage.
// Kept in a plain (non-"use client") module so both the client component that
// renders it and the server page that emits FAQPage JSON-LD can import it —
// values can't cross the client/server boundary out of a "use client" file.

export const faqs = [
  { q: "What is Udyam Registration and is it the same as MSME Registration?", a: "Yes. Udyam Registration is the official government portal for MSME (Micro, Small and Medium Enterprises) registration under the MSMED Act 2006. It replaced the earlier Udyog Aadhaar Memorandum (UAM) system in July 2020. The Udyam Certificate issued after registration is the official proof of MSME status." },
  { q: "Is Udyam Registration mandatory?", a: "Udyam Registration is not legally mandatory for all businesses, but it is effectively mandatory to avail any government MSME benefits — including collateral-free loans, government procurement, subsidies, and scheme benefits. Without registration, businesses cannot access the MSMED Act protection for delayed payments." },
  { q: "What are the investment and turnover limits for MSMEs?", a: "As of the revised 2020 definition: Micro — Investment up to ₹1 Crore and Turnover up to ₹5 Crore; Small — Investment up to ₹10 Crore and Turnover up to ₹50 Crore; Medium — Investment up to ₹50 Crore and Turnover up to ₹250 Crore. Both investment AND turnover criteria must be met — whichever is higher determines the category." },
  { q: "What documents are required for Udyam Registration?", a: "Udyam Registration is a self-declaration process. You need: Aadhaar Card (for OTP verification), PAN Card (mandatory), business name, address, NIC code, bank account details, and approximate investment and turnover figures. No physical document uploads are required on the portal." },
  { q: "How long does Udyam Registration take?", a: "Once you have your Aadhaar OTP and all details ready, the registration is completed in 15–30 minutes online. The Udyam Certificate is issued instantly with a unique Udyam Registration Number. Our team completes the process within 1 working day." },
  { q: "Is Udyam Certificate valid for lifetime?", a: "Yes. The Udyam Certificate has no expiry date and is valid for the lifetime of the enterprise. However, it must be updated annually with turnover and investment data based on the previous year's ITR, and whenever the business details change significantly." },
  { q: "Can a Proprietorship firm register for Udyam?", a: "Yes. All business structures — proprietorship, partnership, LLP, private limited company, OPC, Hindu Undivided Family (HUF), co-operative societies, and trusts — can register under Udyam, provided they meet the investment and turnover criteria." },
  { q: "Can I migrate from old Udyog Aadhaar to Udyam?", a: "Yes, but migration is not automatic. Businesses that registered under the old Udyog Aadhaar system before July 1, 2020 must re-register on the Udyam portal. The old UAM registrations were valid only until March 31, 2021 — after which fresh Udyam Registration is required." },
  { q: "Is Udyam Registration free?", a: "Yes. Udyam Registration on the official government portal (udyamregistration.gov.in) is completely free of charge. There are no government fees. Company Avenue charges a professional service fee for end-to-end assistance, accurate classification, and certificate delivery." },
  { q: "What happens if my business crosses MSME limits?", a: "If your investment or turnover exceeds the MSME threshold during a financial year, you must update your Udyam Registration. You will retain MSME status for that year and the following year (one-year grace period), but after that the enterprise will be re-classified or de-registered." },
  { q: "How does the 45-day payment protection work?", a: "Under the MSMED Act, buyers must pay MSME suppliers within 45 days of delivery/acceptance. If payment is delayed beyond 45 days, the buyer is liable to pay compound interest at 3× the RBI bank rate. MSMEs can file for recovery through the MSME Samadhan portal or file cases before the MSME Facilitation Council." },
  { q: "Can I get a loan just by showing the Udyam Certificate?", a: "The Udyam Certificate makes you eligible for priority sector lending and collateral-free loans under CGTMSE. Banks will still assess your creditworthiness, business plan, and repayment capacity. However, MSME status significantly improves loan approval chances and interest rates." },
];
