// FAQ content for NidhiCompanyPage.
// Kept in a plain (non-"use client") module so both the client component that
// renders it and the server page that emits FAQPage JSON-LD can import it —
// values can't cross the client/server boundary out of a "use client" file.

export const faqs = [
  { q: "What is a Nidhi Company?", a: "A Nidhi Company is a type of Non-Banking Finance Company (NBFC) recognized under Section 406 of the Companies Act 2013 and Nidhi Rules 2014. Its primary purpose is cultivating the habit of saving among its members and accepting deposits and lending exclusively among those members. It operates as a mutual benefit society within a corporate structure." },
  { q: "What is the difference between a Nidhi Company and an NBFC?", a: "While Nidhi Companies are technically a subset of NBFCs, they are exempt from most RBI regulations that apply to regular NBFCs. Regular NBFCs require RBI registration and compliance, whereas Nidhi companies only need MCA registration. Nidhi companies can only deal with members — they cannot deal with the general public, unlike NBFCs." },
  { q: "What is the 200-member requirement?", a: "Within one year of incorporation, a Nidhi Company must have at least 200 members. Each member must hold a minimum of 10 equity shares. Additionally, the company must have net owned funds of at least ₹10 lakhs and the ratio of net owned funds to deposits should not exceed 1:20. These conditions must be reported via Form NDH-1." },
  { q: "Can a Nidhi Company lend to non-members?", a: "No. A Nidhi Company can only accept deposits from and lend to its own members. It cannot deal with the general public. This restriction is fundamental to the Nidhi concept — it is a mutual benefit society. Lending to non-members is a compliance violation and can result in penalties and cancellation of Nidhi status." },
  { q: "What is RBI's role in Nidhi Companies?", a: "While Nidhi Companies are NBFCs by classification, the RBI has specifically exempted them from its core NBFC provisions under Section 406(2) of the Companies Act 2013. This means Nidhi companies do not require RBI registration or approval. However, they must comply with MCA's Nidhi Rules 2014 strictly." },
  { q: "What are the deposit limits for a Nidhi Company?", a: "Nidhi Companies can accept fixed deposits, recurring deposits and savings deposits from members. The maximum net owned fund to deposit ratio is 1:20 — meaning for every ₹1 of net owned funds, the company can accept ₹20 in deposits. Individual deposit limits and maturity periods must comply with the RBI's guidelines as incorporated in the Nidhi Rules." },
  { q: "What interest rates can a Nidhi Company offer?", a: "Nidhi Companies can offer interest rates on deposits up to 2% above the rate offered by nationalized banks on fixed deposits of similar maturity. On loans, the interest charged cannot exceed 7.5% above the highest rate offered on deposits. These caps ensure member protection and prevent exploitation." },
  { q: "What is the compliance calendar for a Nidhi Company?", a: "Nidhi Companies must file: NDH-1 (annual return within 90 days of FY close), NDH-3 (half-yearly return), Annual Return (MGT-7), Financial Statements (AOC-4), Income Tax Return, Director KYC (annually). Additionally, board meetings must be held at least 4 times per year." },
  { q: "What are the penalties for non-compliance?", a: "Non-compliance with Nidhi Rules attracts MCA penalties including monetary fines on the company and its directors. Failure to meet the 200-member or ₹10 lakh NOF requirement within 1 year results in the company not being recognized as a Nidhi — it cannot then conduct Nidhi activities. Repeated non-filing attracts compounding and prosecution." },
  { q: "Can a Nidhi Company be converted to a regular company?", a: "Yes, a Nidhi Company can be converted by amending its MOA to remove the Nidhi objects and complying with regular company requirements. If converting to an NBFC, RBI registration will then be required. Conversion is complex and requires MCA approval. Our team handles the full conversion process including regulatory filings." },
];
