// FAQ content for PartnershipFirmPage.
// Kept in a plain (non-"use client") module so both the client component that
// renders it and the server page that emits FAQPage JSON-LD can import it —
// values can't cross the client/server boundary out of a "use client" file.

export const faqs = [
  { q: "What is a Partnership Firm?", a: "A Partnership Firm is a business structure where two or more persons agree to share profits and losses of a business carried on by all or any one of them acting for all. It is governed by the Indian Partnership Act, 1932 and is one of the oldest and simplest business forms in India." },
  { q: "What is the difference between a Partnership Firm and an LLP?", a: "A Partnership Firm is governed by the Indian Partnership Act 1932, has no separate legal identity and partners have unlimited personal liability. An LLP, governed by the LLP Act 2008, is a separate legal entity with limited liability for partners. LLPs also have mandatory annual MCA filings, while partnership firms have lighter compliance." },
  { q: "What is the minimum and maximum number of partners?", a: "A minimum of 2 persons are required to form a partnership firm. The maximum is 20 partners for general businesses. For banking businesses, the limit is 10 partners. There is no upper cap for professional firms like CA firms under ICAI guidelines." },
  { q: "Is registration of a Partnership Firm mandatory?", a: "No, registration of a partnership firm is not mandatory under the Indian Partnership Act, 1932. However, an unregistered firm cannot file a suit against third parties to enforce its rights. Registration is strongly recommended for practical reasons including bank account opening, government contracts and dispute resolution." },
  { q: "What are the tax implications for a Partnership Firm?", a: "A registered partnership firm is taxed at a flat rate of 30% on its net profits. Partners can receive salary and interest on capital, which are deductible expenses for the firm. Partners are then taxed on their individual income including salary, interest and profit share. A surcharge of 12% applies if income exceeds ₹1 crore." },
  { q: "What should a Partnership Deed contain?", a: "A Partnership Deed should include: names and addresses of all partners, firm name, nature of business, capital contributions, profit/loss sharing ratio, salary and interest provisions, duties and powers of each partner, procedure for admission and retirement of partners, dispute resolution mechanism and dissolution procedure." },
  { q: "Can a Partnership Firm be dissolved easily?", a: "Yes. A partnership firm can be dissolved at any time by mutual consent of all partners. It can also be dissolved by notice (for partnerships at will), by a court order, or upon happening of certain events like insolvency or death of a partner (if the deed so specifies). Dissolution is significantly simpler than winding up a company." },
  { q: "What is unlimited liability in a Partnership?", a: "In a partnership firm, each partner has unlimited personal liability for the firm's debts and obligations. This means creditors can recover dues from partners' personal assets if the firm's assets are insufficient. This is the primary risk of a partnership as compared to LLPs and companies." },
  { q: "Can a Partnership Firm be converted to an LLP?", a: "Yes. A registered partnership firm can be converted to an LLP under Section 55 and Schedule II of the LLP Act, 2008. The process involves filing Form 17 with MCA, along with the partnership deed, consent of all partners and incorporation documents. All assets, liabilities and contracts transfer to the LLP upon conversion." },
  { q: "Does a Partnership Firm need to renew its registration?", a: "A partnership registration is valid for a lifetime once granted by the Registrar of Firms. However, any changes to the firm (partners, address, name, profit sharing) must be intimated to the Registrar by filing Form III (changes), Form IV (dissolution), or Form I amendments." },
];
