// FAQ content for RegisteredOfficeChangePage.
// Kept in a plain (non-"use client") module so both the client component that
// renders it and the server page that emits FAQPage JSON-LD can import it —
// values can't cross the client/server boundary out of a "use client" file.

export const faqs = [
  { q: "How soon must INC-22 be filed after the board resolution?", a: "INC-22 must be filed within 30 days of the date of board resolution approving the change. Any delay attracts a penalty of ₹1,000 per day for as long as the default continues. Both the company and every officer in default are liable for the penalty under Companies Act 2013." },
  { q: "What if the company is changing its state of registered office?", a: "Inter-state registered office change requires Form INC-23 (not INC-22) along with approval from the Regional Director (NCLT). Additionally, publication in at least one English and one vernacular newspaper is mandatory. The process is more complex, typically taking 30-60 days, and requires special resolution by shareholders. Company Avenue handles the complete INC-23 process." },
  { q: "Is a physical office address mandatory as the registered office?", a: "Yes. Under Section 12 of the Companies Act, 2013, the registered office must be a physical address where notices can be served. A PO Box, virtual office (in most cases), or mail forwarding address is not acceptable. The company should be reachable and have some physical presence at the address." },
  { q: "Can I use a home address as the registered office?", a: "Yes — many startups use the founder's or director's home address as the registered office. This is legally valid provided you have the NOC from the property owner (even if you own it, or from parents) and a recent utility bill in the name of the property. There is no regulatory bar on using a residential address." },
  { q: "Do I need a new Certificate of Incorporation after the address change?", a: "No. A new Certificate of Incorporation is not issued solely for a registered office address change. The MCA master data is updated to reflect the new address, and this updated MCA record serves as official proof. The original Certificate of Incorporation remains valid and unchanged." },
  { q: "Is the GST address change automatic after filing INC-22?", a: "No. The ROC/MCA and GST systems are entirely separate. After the INC-22 is approved and MCA address is updated, you must separately file Form GST REG-14 on the GST portal to update your GSTIN address. Some states may require fresh GST registration if you move to a different state." },
  { q: "How is the bank account address updated?", a: "The bank is notified separately — there is no automatic bank update from MCA. You need to submit a request to your bank branch with a certified copy of the board resolution and the new address proof (utility bill). Each bank has its own internal process, but the board resolution is the key document." },
  { q: "Is the landlord's NOC mandatory if the property is rented?", a: "Yes. If the new registered office is on a rented or leased property, a written No Objection Certificate (NOC) from the property owner is mandatory for the INC-22 filing. The NOC must state that the owner consents to the company using the premises as its registered office. Without it, the ROC may raise a deficiency notice." },
  { q: "What is the penalty for not filing INC-22 within 30 days?", a: "Under Section 12(8) of the Companies Act, 2013, the company and every officer in default is liable to a penalty of ₹1,000 for every day the default continues, up to ₹1,00,000. Beyond penalties, prolonged delay can attract ROC show-cause notices and may affect MCA annual filings." },
  { q: "Is a PO Box acceptable as a registered office address?", a: "No. A PO Box is categorically not acceptable as a registered office. The Companies Act requires a physical address where legal notices can be served. Similarly, virtual offices are generally not accepted by many ROCs unless supported by a proper rental agreement and evidence of physical use." },
];
