// FAQ content for Section8CompanyPage.
// Kept in a plain (non-"use client") module so both the client component that
// renders it and the server page that emits FAQPage JSON-LD can import it —
// values can't cross the client/server boundary out of a "use client" file.

export const faqs = [
  { q: "What is a Section 8 Company?", a: "A Section 8 Company is a non-profit organization registered under the Companies Act, 2013. It is formed for charitable, educational, scientific, religious, social welfare or environmental purposes. Unlike regular companies, it cannot distribute profits to its members — all surplus must be applied toward its stated objectives." },
  { q: "What is the difference between a Section 8 Company, a Trust and a Society?", a: "A Section 8 Company is governed by MCA under the Companies Act 2013 — it has higher credibility, stricter governance and is preferred for CSR funding and FCRA registration. A Trust is governed by the Indian Trusts Act 1882 and is simpler to form. A Society is governed by the Societies Registration Act 1860 at the state level. Section 8 companies are generally preferred for their transparency and accountability." },
  { q: "Can directors of a Section 8 Company draw a salary?", a: "Yes. Directors and employees of a Section 8 Company can receive reasonable remuneration for services rendered. However, they cannot receive any dividend or profit share. Salaries must be commensurate with the role and disclosed in financial statements. Excessive compensation can be questioned by authorities." },
  { q: "What are the benefits of 12A and 80G registration?", a: "12A registration grants income tax exemption to the Section 8 company — its income used for charitable purposes is not taxed. 80G registration allows donors to claim a deduction of 50% of their donation amount from their taxable income. These two registrations together make the organization highly attractive to individual and corporate donors." },
  { q: "Can a Section 8 Company receive foreign funding?", a: "Yes, but only after obtaining FCRA (Foreign Contribution Regulation Act) registration. FCRA registration is granted by the Ministry of Home Affairs and allows the organization to receive donations, grants and contributions from foreign citizens and organizations. FCRA registration requires the organization to have at least 3 years of existence." },
  { q: "Is a Section 8 Company eligible to receive CSR funds?", a: "Yes. Companies with mandatory CSR obligations under the Companies Act can direct funds to registered Section 8 companies if they are included in Schedule VII activities. The Section 8 company must have a valid 12A and 80G certificate and conduct activities specified in Schedule VII." },
  { q: "What is the minimum number of members required?", a: "A Section 8 Company requires a minimum of 2 directors and 2 members for private (non-public) status. There is no maximum member limit. A single person cannot incorporate a Section 8 company — it requires at least two individuals committed to the charitable cause." },
  { q: "Can a Section 8 Company distribute profits?", a: "No. Distribution of profits, dividends or surplus to members or directors is strictly prohibited for Section 8 companies. Any profits or surplus generated must be used exclusively for the promotion of the charitable objects stated in the MOA. Violation of this provision can result in revocation of the licence and penalties." },
  { q: "Can a Section 8 Company be wound up?", a: "Yes. A Section 8 Company can be wound up voluntarily or compulsorily. However, upon winding up, the assets cannot be distributed among members. The remaining assets must be transferred to another Section 8 company with similar objects or to the government. This ensures the charitable mission continues." },
  { q: "What are the annual compliance requirements?", a: "A Section 8 Company must file annual returns (MGT-7), financial statements (AOC-4) and income tax returns each year. If 12A and 80G registered, it must also file Form 10B (audit report) with the Income Tax Department. Directors must comply with DIN KYC annually. Board meetings must be held at least twice a year." },
];
