// FAQ content for SoleProprietorshipPage.
// Kept in a plain (non-"use client") module so both the client component that
// renders it and the server page that emits FAQPage JSON-LD can import it —
// values can't cross the client/server boundary out of a "use client" file.

export const faqs = [
  { q: "What is a Sole Proprietorship?", a: "A Sole Proprietorship is the simplest business form in India where one individual owns, manages and controls the entire business. There is no distinction between the owner and the business — legally, they are the same person. The owner enjoys all profits but is also personally liable for all debts and obligations of the business." },
  { q: "Does a sole proprietorship require formal registration?", a: "There is no single law governing sole proprietorships in India. There is no mandatory 'proprietorship registration'. However, to operate legitimately, a proprietor typically obtains a GST registration, Udyam (MSME) certificate, shop and establishment license, or professional tax enrollment — which collectively establish the existence of the business." },
  { q: "What is the liability risk in a proprietorship?", a: "The primary risk in a proprietorship is unlimited liability. If the business incurs debts or legal obligations it cannot meet, creditors can recover dues from the owner's personal assets including savings, property and investments. This is a significant risk for businesses dealing in credit or litigation-prone industries." },
  { q: "Can a proprietorship be converted to a company?", a: "Yes. A proprietorship can be converted to a Private Limited Company or LLP when the business grows. Assets and liabilities can be transferred, and the business name can be retained. We handle the full conversion process including incorporation, asset transfer documentation and PAN/TAN migration." },
  { q: "Is GST registration mandatory for a proprietorship?", a: "GST registration is mandatory if annual turnover exceeds ₹40 lakhs (goods) or ₹20 lakhs (services). It is also mandatory for inter-state supplies, e-commerce sellers and certain notified categories regardless of turnover. Voluntary registration is also possible and is recommended if your clients are GST-registered businesses." },
  { q: "How is a proprietorship taxed?", a: "A proprietorship is not taxed separately. The business income is included in the owner's personal income and taxed at individual income tax slab rates (0% to 30% + surcharge). The owner can file ITR-3 for business income or ITR-4 under the presumptive taxation scheme if turnover is within the specified limits." },
  { q: "Can a proprietor open a business bank account?", a: "Yes. A proprietor can open a current account in the business name at any bank. Banks typically require GST certificate, Udyam registration, or shop & establishment license as proof of business existence. We assist with the bank account opening process as part of our package." },
  { q: "Should a proprietorship get MSME/Udyam registration?", a: "Absolutely. Udyam (MSME) registration is free, done entirely online and provides numerous benefits: priority lending by banks, subsidies on patents and trademarks, access to government tenders, eligibility for MSME schemes and protection against delayed payments. We recommend it for all proprietorships." },
  { q: "Can a proprietor run multiple businesses?", a: "A sole proprietor can run multiple businesses under different trade names, but they all remain part of the same legal entity — the individual. Each business may require separate GST registration if they are in different states or different business verticals. All income is aggregated for tax purposes." },
  { q: "How is a proprietorship dissolved?", a: "Dissolving a proprietorship is simple. Close the bank account, surrender GST registration, close Udyam registration, file final income tax return and notify relevant authorities. There is no formal 'winding up' process as required for companies or LLPs. Our compliance team handles the complete closure procedure." },
];
